### PR TITLE
ctest for CML LDPC

### PR DESCRIPTION
**Pull request by drowe67**
Test installation of CML library, and run LDPC unit test

### CODE REVIEW

**Comment by drowe67** [comment]
@darksidelemm @tmiw could you pls try this PR on OSX?

**Comment by tmiw** [comment]
@drowe67, I'm getting test failures because I apparently don't have Octave installed. I'm still working through various MacPorts failures trying to fix that and will let you know once I have usable "make test" output.

**Comment by drowe67** [comment]
@tmiw thanks for those tests.  @darksidelemm also had some problems with the installation of the CML code (see top of octave/ldpc.m) required for the first ctest on his OSX machine.  

Ideally, it would be nice to automate the installation of the packages required to run the ctests on OSX (and indeed Ubuntu) to support these tests  - making it easy for developers.  At the moment we have that installation automated or just the Travis runs.

**Comment by darksidelemm** [comment]
Sorry, havent tested this yet. The issue I had was when building the .mex files within octave, and was solved by removing the `#include <matrix.h>` lines throughout the CML library.
I suspect the issue was something to do with header precedence, and may be a compiler specific thing.

**Comment by tmiw** [comment]
@darksidelemm, matrix.h eventually includes some C++ specific headers (namely cassert), which don't work when generating C code. CML compiled fine once matrix.h was removed/commented out.

@drowe67, good news and bad news. The good news is that the newly added test seems to work on OSX. The bad news is that there are a fair number of other failures (including two tests that caused segfaults):

> 65% tests passed, 14 tests failed out of 40
> 
> Total Test time (real) =  43.98 sec
> 
> The following tests FAILED:
	  2 - test_codec2_700c_octave_port (Failed)
	  4 - test_COHPSK_modem_octave_port (Failed)
	  5 - test_OFDM_modem_octave_port (SEGFAULT)
	  6 - test_OFDM_modem_octave_port_Nc_31 (SEGFAULT)
	 10 - test_OFDM_modem_fading_BER (Failed)
	 11 - test_OFDM_modem_phase_est_bw (Failed)
	 12 - test_OFDM_modem_time_sync_700D (Failed)
	 13 - test_OFDM_modem_fading_DPSK_BER (Failed)
	 25 - test_memory_leak_FreeDV_1600_tx (Failed)
	 26 - test_memory_leak_FreeDV_1600_rx (Failed)
	 27 - test_memory_leak_FreeDV_700D_tx (Failed)
	 28 - test_memory_leak_FreeDV_700D_rx (Failed)
	 38 - test_est_n0 (Failed)
	 40 - test_700c_eq (Failed)
Errors while running CTest
make: *** [test] Error 8

Anyway, we could maybe handle the other failures in another PR since I don't think they impact this one. Thoughts?

**Comment by drowe67** [comment]
Thanks for trying that @tmiw :+1: 

I think it will be a big job to get them all running on OSX, so as you suggest we don't need to look into it any further in this PR.  I imagine it's a whole lot of packages and configuration.  They run cleanly on Ubuntu and Travis so that's probably enough for now :smile: 

If any OSX developers get really keen on the detail covered by the tests I am sure they can get them running.

**Pull request merged**
