### PR TITLE
QAM and Packet Data for OFDM 2

### PR DESCRIPTION
**Pull request by drowe67**
Octave simulation of coded QAM16. Continuing on from https://github.com/drowe67/codec2/pull/110

Todo
1. ~~QAM16 Amplitude estimation~~
1. ~~QAM16 working on multipath channels~~
1. ~~QAM16 ofdm_tx/rx and ofdm_ldpc_tx/rx working~~
1. ~~PER of 10% at SNR 15dB~~

Further Work:

1. Try APSK
1. OTA test using Octave and stored files
1. Port to C and build up FreeDV mode

### CODE REVIEW

**Comment by drowe67** [comment]
I have developed a new amplitude estimator that improves QAM16 performance.  QPSK modes also use amplitude estimates to help with LDPC decoding on multipath channels.

Using this test:
```
octave:127> ofdm_ldpc_tx("test.raw", "700D",60,4,'mpp')
octave:128> ofdm_ldpc_rx("test.raw", "700D")
```

1. Original 700D estimator (as per current C code):
   ```
   Raw BER..: 0.0771 Tbits: 89250 Terrs:  6884
   Coded BER: 0.0280 Tbits: 42000 Terrs:  1176
   Coded PER: 0.1968 Pckts:   376 Perrs:    74
   ```
1.  New estimator (used for QAM16 and data modes):
    ```
    Raw BER..: 0.0771 Tbits: 89250 Terrs:  6884
    Coded BER: 0.0317 Tbits: 42000 Terrs:  1330
    Coded PER: 0.2367 Pckts:   376 Perrs:    89
    ```

So a bit worse for the new estimator.  That's curious, but there are several other differences in the 700D waveform, such as pilot symbol rate, and a much shorter (single modem frame) packet.  So we will keep the original amplitude estimator for 700D.

**Comment by drowe67** [comment]
With the new amplitude estimator we are getting reasonable results for QAM16 on multipath channels using this 60 second test:
```
octave:144> ofdm_ldpc_tx("test.raw", "qam16",60,18,'mpp')
octave:145> ofdm_ldpc_rx("test.raw", "qam16")
```

1. AWGN 12dB:
   ```
   Raw BER..: 0.0272 Tbits: 316800 Terrs:  8623
   Coded BER: 0.0000 Tbits: 247680 Terrs:     1
   Coded PER: 0.0083 Pckts:   120 Perrs:     1
   ```
1. MPP 18dB
   ```
   Raw BER..: 0.0328 Tbits: 308880 Terrs: 10145
   Coded BER: 0.0135 Tbits: 241488 Terrs:  3260
   Coded PER: 0.2393 Pckts:   117 Perrs:    28
   ```
1. MPM 18dB:
    ```
    Raw BER..: 0.0245 Tbits: 316800 Terrs:  7772
    Coded BER: 0.0080 Tbits: 247680 Terrs:  1987
    Coded PER: 0.1750 Pckts:   120 Perrs:    21
    ```
1. MPG 18dB:
   ```
   Raw BER..: 0.0321 Tbits: 311520 Terrs: 10002
   Coded BER: 0.0133 Tbits: 243552 Terrs:  3230
   Coded PER: 0.1780 Pckts:   118 Perrs:    21
   ```

Note the PERs are all around 20%, indicating the modem works indepentently of the fading channel parameters.  A SNR of 18dB and PER of 20% is higher than the target 10% @ 15dB.

Multipath operating points are usually 6-8dB above AWGN.  However with these waveforms we are running out of "headroom", real world HF channels are unlikely to have SNRs about 15dB.

Options include:
1. Letting the ARQ protocol handle the missing packets through retransmission.
1. A longer FEC codeword at the same code rate.
1. A higher code rate.

**Comment by drowe67** [comment]
@srsampson suggest you don't merge any of this into your branch as it's still quite experimental.  Best to get the initial set of changes ported to C as a first step.

**Comment by srsampson** [comment]
> @srsampson suggest you don't merge any of this into your branch as it's still quite experimental. Best to get the initial set of changes ported to C as a first step.

Copy that. I've been out of office the last week. Kind of getting back into it slowly.

**Comment by drowe67** [comment]
@billcowley I'm trying a longer code, at about the same 0.8 rate.  I'm using the CML DVBS2 codeword which is 16200 bits long, a packet duration of 3.1s.  The MPP channel has 1Hz Doppler.
```
octave:35> ofdm_ldpc_tx("test.raw", "qam16c2",60,18,'mpp')
ofdm_ldpc_rx("test.raw", "qam16c2")
``` 
1. 18dB MPP:
   ```
   Raw BER..: 0.0304 Tbits: 310992 Terrs:  9461
   Coded BER: 0.0028 Tbits: 239400 Terrs:   680
   Coded PER: 0.0526 Pckts:    19 Perrs:     1
   ```
1. 16dB MPP:
   ```
   Raw BER..: 0.0440 Tbits: 310992 Terrs: 13677
   Coded BER: 0.0120 Tbits: 239400 Terrs:  2869
   Coded PER: 0.2632 Pckts:    19 Perrs:     5
   ```

So the longer codeword gives us an improvement at 18dB, but I still haven't reached my target of 10% PER @ 15dB SNR. In the 16dB results the raw BER is at about the limit of this code.  That suggests that no matter how long the codeword/interleaver is, it won't be able to correct the errors.  So time to lower the code rate!

**Comment by drowe67** [comment]
OK I changed the code rate to 0.6, and hit my goal at 15dB:
```
Raw BER..: 0.0523 Tbits: 310992 Terrs: 16254
Coded BER: 0.0000 Tbits: 184680 Terrs:     0
Coded PER: 0.0000 Pckts:    19 Perrs:     0
```
The PER exceed 10% at 13dB SNR. However the payload data rate dropped from 4100 to 3100 bits/s (23 kbyte/minute).  I think that's acceptable, for [comparison](https://www.winlink.org/sites/default/files/downloads/a_winlink_digital_mode_performance_comparison_based_on_the_ionos_hf_vhf_channel_simulator_-_may_18_2020.pdf):

| Waveform | Bytes/min on MPP @15dB |
| --- | --- |
| ARDOP | 0 |
| VARA | 2700 |
| Pactor 3 | 3700 |
| Pactor 4 | 500 |
| Codec 2 qam16c2 | 20,000 |

I took 10% off the Codec 2 throughput to account for overheads (such as ARQ).  A very satisfactory result.

Waveform details in the [spreadsheet](https://github.com/drowe67/codec2/blob/dr-qam/doc/modem_codec_frame_design.ods).

**Comment by drowe67** [comment]
@srsampson I'm finding it easy and easier to work with our OFDM modem :+1:.  Each waveform takes less time to develop :grinning:

**Comment by drowe67** [comment]
@billcowley thanks for the APSK SER script.  Could you pls tell me how I can use that for BER estimation?  Feels like something I should know how to do by now .... :thinking: 

I note also that CML does APSK.  We could test them side by side with a modification to the symbol rate simulation [qam16_test.m](https://github.com/drowe67/codec2/blob/master/octave/qam16_test.m)

Are the expected differences between QAM and APSK More subtle that a BER v Eb/No test on AWGN channels?  For example do larger differences become apparent when used with a PA?

**Comment by billcowley** [comment]
@drowe67 Hi David. Re your good questions above.  For QAM at reasonable SNRs we can expend 1 bit error per symbol error (assuming grey mapping). This is not the case with APSK, especially higher order APSK. I'm expecting 16 APSK uncoded BER will be similar to the SER - but this would be good to simulate.   Re the second  - good idea.  Should I try to take a look at this?   

Re the 3rd question:  certainly!   APSK was designed to give better performance with satellite TWTs where power efficiency is critical and non-linearity is a big issue.  We assume that it will also help in solid-state PAs, say in amateur transceivers.  But dealing with NL effects is a very board area, -with constellation design, equalisers, pre-equalisers (both at symbol and sample levels) + more advanced methods.  This has been the subject of many PhDs! A good start would be over-the-air tests with PRBS sequences and typical transceivers, aiming to plot scatter diagrams showing the Rx constellations ..

**Comment by drowe67** [comment]
Hi @billcowley - yes please feel free to add APSK to [qam16_test.m](https://github.com/drowe67/codec2/blob/master/octave/qam16_test.m) - just use ```dr-qam``` branch and this PR.  That would be great :+1: 

That's a fine idea to test a few SSB radio PAs with various constellations and I would be happy to work with you on that.  The related topic of PAPR and OFDM has recently come up on the Codec 2 list, I am also keen to look into this with some simulations and on-air tests.  I go around in circles when I think about it, e.g. compress/clip OFDM, BER increases, but EIRP also increases.  A harmonic series generating time domain impulses is also very similar to my speech work.

**Pull request merged**
