### PR TITLE
4FSK LLR estimation Part 2

### PR DESCRIPTION
**Pull request by drowe67**
Following on from https://github.com/drowe67/codec2/pull/129

## Instructions

1. Run tx and rx:
   ```
   octave:46> fsk_lib_ldpc_tx("test.raw")
   octave:48> fsk_lib_ldpc_rx("test.raw")
   Fs: 8000 Rs: 100 frames received:   8
     Uncoded: nbits:   3584 nerrs:      0 ber: 0.000
     Coded..: nbits:   2048 nerrs:      0 ber: 0.000
     Coded..: npckt:      8 perrs:      0 per: 0.000
   ```
1. Introduce some simulated noise for testing:
   ```
   octave:49> fsk_lib_ldpc_tx("test.raw",6)
   Fs: 8000 Rs: 100 EbNodB: 6.0  EcNodB: 3.0 frames transmitted:  10
   octave:50> fsk_lib_ldpc_rx("test.raw")
   Fs: 8000 Rs: 100 frames received:   8
     Uncoded: nbits:   3584 nerrs:     68 ber: 0.019
     Coded..: nbits:   2048 nerrs:      0 ber: 0.000
     Coded..: npckt:      8 perrs:      0 per: 0.000
   ``` 
1. Simulate a 1E6*(8010-8000)/8000=1250 ppm timing offset:
   ```
   $ sox -t .s16 -r 8000 test.raw -t .s16 -r 8010 test1.raw
   octave:51> fsk_lib_ldpc_rx("test1.raw")
   Fs: 8000 Rs: 100 frames received:   8
     Uncoded: nbits:   3584 nerrs:     58 ber: 0.016
     Coded..: nbits:   2048 nerrs:      0 ber: 0.000
     Coded..: npckt:      8 perrs:      0 per: 0.000
   ```

## 4FSK/LLR work TODO

1. ~~```SNRLin/v_est``` estimators in ```fsk_lib.m``~~
1. ~~Octave simulation of 4FSK modem with LDPC, compare BER to these simulations.~~
1. ~~OTA test with octave simulation to flush out any real world issues early.~~
1. ~~```SNRLin/v_est``` estimators in ```fsk.c```~~
1. Unit test for ```SNRLin/v_est```
1. ~~Port CML C routines for ```SoMap/DemodFSK```~~.
1. ~~Unit test for C 4FSK -> LDPC decoder, compare to these simulations~~.
1. ~~Build/test real world C waveform that integrates frame sync/4FSK modem/LDPC~~ , compare to these simulations.
1. ~~Run stm32 tests as we have messed with float/double interface in ```ldpc_``` that are used for stm32 test vectors.~~

### CODE REVIEW

**Comment by drowe67** [comment]
@billcowley I'm building up the tx/rx Octave scripts here.

**Comment by drowe67** [comment]
@billcowley - pls see instructions above for tx and rx scripts.  The rx script generates a few plots.

I'm not sure if the EcNodB and EbNodB values make sense - but the uncoded BER seems to match EbNodB.  Pls feel free to adjust that (or any part) of the code if I haven't interpreted it correctly.

It would be useful for each of us to do an OTA test run with a local Tx/Rx to make sure all the line interfaces are working correctly.

**Comment by billcowley** [comment]
@drowe67  Antenna  is installed on upper roof, towards your QTH!  

I've tried your scripts above and that works fine: record to file then play from file.  The "6dB" file sounds impressively noisy thr the speakers.  

For a local "OTA" test,  so far:  play file in one cmd window, rec to 2nd file in another window, with audio loop back cable from headphones to mic.  [I'm sure that sox can do this in one line with the right params.]   I had to wind the levels down to avoid lots of clipping.    Spectrum looks OK but "no frames detected"      Can you try this ? 

Haven't tried connecting to '817 yet.

**Comment by billcowley** [comment]
@drowe67 re the audio loopback test above -- simple problem:  the recorded file from the mic input was using 2 channels ie needs -c 1  in the sox command - now it's giving a very small error rate, even for clean tx signal.  SNR estimate is high. Might be useful to look at where these bit errors are occurring - ie are they randomly distributed?       [BTW -n spectrogram option of sox is useful.]

**Comment by drowe67** [comment]
Hi @billcowley,

Re Eye diagram (or similar), ```fsk_demod_file.m``` shows how to log and plot plot the integrator (filter) outputs ```f_int_resample_log```.  Pls feel free to add that plot if you like.
 
> Might be useful to look at where these bit errors are occurring - ie are they randomly distributed?
 
Does Fig 3 Uncoded Errors help?  It may be the first or last frames.

Can you pls post your sox record line here?  I always like to write them down so I can remember them :-)

**Comment by billcowley** [comment]
**Initial Local RF Loopback Testing of Coded 4FSK**

Tx side:  Using RPI as audio source:  ensure sox is installed, then using inbuilt headphone jack 
"amixer cset numid=3 1"   << sets audio output to analog jack, not HDMI
"amixer set Master 75%"  << default output level is 0% !!
"play -t .s16 -r 8000 -c 1 test60.raw   repeat 10"   << repeat *10 the test (60dB) FSK file in mono

After plugging in the SignaLink USB interface, the default output changes from headphone jack (card 0)to USB codec (card 1).  "aplay -l" will list audio devices.  Anyway the device can be selected eg by "AUDIODEV=hw:1 play -t .s16 -r 8000 -c 1 --vol 4 test60.raw"   The --vol option is needed to turn on the PTT in the SignaLink interface and still results in 0% clipping.    The FT817 is set to "DIG" mode, transmitting on 145.3 MHz about 0.5 W into a dummy load.  

Rx side:   Initially using SDRplay with CubicSDR running under OSX. Couldn't get sensible results - first it just seemed to be frequency offsets, but then other issues.  Then tried RTL dongle with GQRX (running under OSX) - this worked :)  No errors (but link distance only 2m!)  Needed LSB Rx mode on GQRX (I guess this can be changed on '817 - probably should use USB?)  Audio file from GQRX converted to raw via 
"sox gqrx_test1.wav -t .s16 -r 8000 -c 1 gqrx_test1.raw"   then used fsk_lib_ldpc_rx as above. Sox says the .way file is 2 channels - but still works (can GQRX store demod output in mono?)

This test gave a 30dB SNRest (and the scale on this plot needs fixing).  The tone frequencies were about 200 Hz higher than the Tx signal which seem high as the NooElec RTL dongle is fairly accurate, but the demo still locked OK.

**Comment by drowe67** [comment]
@billcowley that's a great test well done :+1: 

OK that's interesting, I didn't know about the cmd line tricks to configure the sounds cards.  I use ```play``` then the Ubuntu control panel to select the sound card.  ```alsamixer``` is useful to adjust levels (e.g. when running freedv-gui).

Does repeating the sound file introduce any bit errors?  Not sure if that would result in gaps between frames as the file rolls over.

IIRC I use USB for the FT817 on FreeDV, not sure what analog processing DIGI mode implies.  

30dB SNR and 200Hz freq offset sounds about right to me for an Over the Bench (OTB) test :slightly_smiling_face: A similar OTB test with FreeDV  waveforms between my FT817 and IC7200 results in a maximum of 14dB SNR, which I suspect is due to the cyrstal filter ripple and passband slope.  SDRs with flat responses tend to do better.

Looks like you're all set!

**Comment by billcowley** [comment]
@drowe67 Excellent result this morning with first OTA transmission of coded 4FSK, NLOS path 145.3 MHz - for the record:  

> octave:302> fsk_lib_ldpc_rx("davidrx2.raw")
> Fs: 8000 Rs: 100 frames received:  13
>   Uncoded: nbits:   6144 nerrs:      0 ber: 0.000
>   Coded..: nbits:   3328 nerrs:      0 ber: 0.000
>   Coded..: npckt:     13 perrs:      0 per: 0.000
This test was about 1W Tx into vertical; Rx antenna used 6 element yagi:   But signal too clean - as there are no uncoded errors!
oth2

Following test with reduced power had good SNR but 'no frames detected' - I guess the '817 change to USB instead of DIG mode has inverted the spectrum again?

**Comment by drowe67** [comment]
Hi @billcowley - in https://github.com/drowe67/codec2/pull/136/commits/a0f965d404a8a306c452d0273ee94cd459b722ac I've changed the command lines to support our test options without code changes, for example:

1. Vanilla Rs=100, rate 0.5 code:
```
fsk_lib_ldpc_tx("test.raw")
fsk_lib_ldpc_rx("test.raw")
```
1. Rs=400, rate 0.75 code:
```
fsk_lib_ldpc_tx("test.raw",num_frames=10,Rs=400,rate=0.75)
fsk_lib_ldpc_rx("test.raw",Rs=400,rate=0.75)
```

Look forward to some more tests this afternoon - will catch up on line about 1600 hours :satellite:

**Comment by billcowley** [comment]
@drowe67     Thanks David, but 'fsk_lib_ldpc_tx("test.raw",num_frames=10,Rs=400,rate=0.75)'   still gives the 'error: Fs/Rs must be an integer' problem    Talk  with you around 4pm

**Comment by drowe67** [comment]
@billcowley @darksidelemm I have made some progress in porting the 4FSK/LLR stuff to C.

The command line is quite a mouthful:
```
$ cd codec2/build_linux
$ ./src/ldpc_enc /dev/zero - --code HRAb_396_504 --testframes 200 | ./src/framer - - 504 5186 | ./src/fsk_mod 4 8000 100 1000 100 - - | ./src/cohpsk_ch - - -25 --Fs 8000  | ./src/fsk_demod -s 4 8000 100 - - | ./src/deframer - - 504 5186  | ./src/ldpc_dec - /dev/null --code HRAb_396_504 --testframes
<snip>
Raw   Tbits:  99792 Terr:   3425 BER: 0.034
Coded Tbits:  78408 Terr:    275 BER: 0.004
      Tpkts:    198 Tper:     23 PER: 0.116
```

`framer` and `deframer` are new - they add and strip a unique word (16 bits `0x5186`), and handle frame sync on the command line.  I'm just using some existing LDPC codes atm, haven't ported the latest codes to C yet.  `cohpsk_ch` is a channel simulator - the `-25` argument in the example above is the noise level you can tweak. Note above it's also starting to get packet errors with the raw BER about 3%, about right for a rate 0.8 code.

 @billcowley - it's falling over with your `SNRest` about 7dB, just like Octave, which gives me some confidence.  You can print SNRest out from this line in `fsk_demod` if you like:
```
//fprintf(stderr, "v_est: %f SNRest: %f\n", fsk->v_est, fsk->SNRest);            
```

**Comment by drowe67** [comment]
Hi @billcowley - do we need both `load H_256_512_4.mat` & `load H_256_512_5.mat`?

**Comment by drowe67** [comment]
Extra codes added....

```
$ cd codec2/build_linux/src
$ ./ldpc_enc --listcodes

H2064_516_sparse     rate 0.80 (2580,2064) 
HRA_112_112          rate 0.50 (224,112) 
HRAb_396_504         rate 0.79 (504,396) 
H_256_768            rate 0.33 (768,256) 
H_256_512_4          rate 0.50 (512,256) 
HRAa_1536_512        rate 0.75 (2048,1536) 
```
You need to change the `framer/deframer` length parameter to match the code, `512` for this code:
```
$ ./ldpc_enc /dev/zero - --code H_256_512_4 --testframes 200 | ./framer - - 512 5186 | ./fsk_mod 4 8000 100 1000 100 - - | ./cohpsk_ch - - -24 --Fs 8000  | ./fsk_demod -s 4 8000 100 - - | ./deframer - - 512 5186  | ./ldpc_dec - /dev/null --code H_256_512_4 --testframes
```

**Comment by billcowley** [comment]
> Hi @billcowley - do we need both `load H_256_512_4.mat` & `load H_256_512_5.mat`?

@drowe67    Hi David - looks like you are making great progress!   Re these short, rate 1/2 codes, after some recent testing I wrote this to Mark:    "for 1/2 rate I suggest H_128_256_5 and H_256_512_4 (both in my Horus-FEC github repo)"        Cheers, Bill

**Pull request merged**
