### PR TITLE
Convert new modem changes from Octave to C99

### PR DESCRIPTION
**Pull request by srsampson**
Starting with dr-qam branch with its changes to ofdm_lib.m

### CODE REVIEW

**Comment by drowe67** [comment]
Nice work @srsampson :+1: 

I'll merge dr-qam later today as it's getting a bit long, that should make it easier to see what's going on with this PR.

**Comment by srsampson** [comment]
> Nice work @srsampson 
> 
> I'll merge dr-qam later today as it's getting a bit long, that should make it easier to see what's going on with this PR.

At this stage I was mostly just trying to make sure I had all the state variables (config and ofdm) in ofdm_internal.h covered.

I noticed with ofdm->samplespersymbol we could replace all the (ofdm-m + ofdm->ncp) calcs.

**Comment by drowe67** [comment]
> I noticed with ofdm->samplespersymbol we could replace all the (ofdm-m + ofdm->ncp) calcs.

Yep - this has been a useful opportunity to think about constants/names of variables.  A second lap around the modem :smile: code ...

**Comment by srsampson** [comment]
Checked the Unique Word indexing using a quicky test program (bps = 2):
```
tx_uw_syms[0] = 1.000000 + 0.000000 * I
tx_uw_syms[1] = 1.000000 + 0.000000 * I
tx_uw_syms[2] = 1.000000 + 0.000000 * I
tx_uw_syms[3] = 1.000000 + 0.000000 * I
tx_uw_syms[4] = 1.000000 + 0.000000 * I
uw_ind[0] = 18
uw_ind[1] = 17
uw_ind[2] = 36
uw_ind[3] = 35
uw_ind[4] = 54
uw_ind[5] = 53
uw_ind[6] = 72
uw_ind[7] = 71
uw_ind[8] = 90
uw_ind[9] = 89
uw_ind_sym[0] = 9
uw_ind_sym[1] = 18
uw_ind_sym[2] = 27
uw_ind_sym[3] = 36
uw_ind_sym[4] = 45
```

**Comment by drowe67** [comment]
@srsampson I merged with master to get rid of some of the noise from all those files I changed in https://github.com/drowe67/codec2/pull/110.

**Comment by drowe67** [comment]
@srsampson I have some leave from $dayjob next week so can help you out with this PR (if you like).

I'm pretty happy with how the QAM stuff is going over on https://github.com/drowe67/codec2/pull/130, however still suggest you don't merge any of that until the baseline C port here is stable.

**Comment by srsampson** [comment]
I've been busy. I'll probably get some code in tomorrow as it is hot and humid. I want to fix the ofdm_mod and odm_demod programs to use the new default settings and use the NULL pointer to trigger that. Kind of half-done right now. Then there's the main code, oh boy...

**Comment by srsampson** [comment]
> @srsampson I have some leave from $dayjob next week so can help you out with this PR (if you like).
> 
> I'm pretty happy with how the QAM stuff is going over on #130, however still suggest you don't merge any of that until the baseline C port here is stable.

I have the Octave code in a diff file, and was using that as a guide. But you probably can do more and faster, so don't worry about me when producing code. I'll try and keep up :-)

**Comment by drowe67** [comment]
> I've been busy. I'll probably get some code in tomorrow as it is hot and humid. 

I'm camping this weekend at "Wilpena Pound" (Google it), 13C and light rain atm!

>I want to fix the ofdm_mod and odm_demod programs to use the new default settings and use the NULL pointer to trigger that. Kind of half-done right now. Then there's the main code, oh boy...

Cool.  Well just work on it if you feel like it, it's a hobby after all :smile: 

I'll touch base next week and see if there is something I can help with.  I got into quite a bit of trouble myself with these recent changes, but found the ctests really helpful.  I backed out of changes a few times to something that worked, then moved fwd again, just making small changes and running the ctests each time.

I *am* impressed how flexible our modem design is proving.  We've done well :+1:

**Comment by drowe67** [comment]
Hi @srsampson 

I had all tests passing in387a0603a but I think we just committed simultaneously so it might need some untangling.

1. So I created a new branch off master then manually added each of your changes, running  ```ctest -R test_OFDM``` every few lines, and committing if I passed.  I then copied the final result over to yr branch.
1. I haven't added the QAM16 functions on this pass, pls feel free to add them (but perhaps in a ```qam16.c``` file with a test as per the latest Octave).
1. There was also a bug in the UW bit packing, I've left that as a TODO for now.
1. I've found the ctests  really useful for this sort of work, e.g. when I am hacking Octave I keep running them to make sure i don't break the C port to legacy waveforms" .  Tiny changes, then run the ctests.

I quite enjoy a good bug hunt, at least when finding the bugs is systematic like this. Whiled away a Friday afternoon.... :grinning: 

Guess the next step is to build up the functionality for one of the data modes, perhaps the tx side first, and see if it can interoperate with the Octave version.

**Comment by srsampson** [comment]
I'm editing the tofdm.c file online. This is a bad practice, ha! My eyes require a good editor.

**Comment by srsampson** [comment]
I'm finished editing for now. Getting an assert on line 306 in tofdm.c but time for bed. My body clock is off again.

**Comment by srsampson** [comment]
I was looking closer at your code changes, and it looks like you are backing out a lot of my changes, probably to get the thing to pass travis. So I'll stop making changes to those areas until we get to passing again.

**Comment by drowe67** [comment]
Hi @srsampson,

> I was looking closer at your code changes, and it looks like you are backing out a lot of my changes, probably to get the thing to pass travis. So I'll stop making changes to those areas until we get to passing again.

Pretty sure I captured all your changes except those mentioned in https://github.com/drowe67/codec2/pull/126#issuecomment-656540067.  However I applied them manually step by step to keep passing ctests, so a diff might be confusing.   Most of them were in ```ofdm_create```.

The ctests pass in https://github.com/drowe67/codec2/pull/126/commits/387a0603a9bb4d44aa6f6056a9b994cb1e782e21, and the only changes since then have been in ```tofdm.c```.  Would you like me to fix ```tofdm.c``` or do you want to look at it?  

Suggest the same process, start with https://github.com/drowe67/codec2/pull/126/commits/387a0603a9bb4d44aa6f6056a9b994cb1e782e21, then gradually apply the changes to ```tofdm.c```, running:
 ``` 
$ ctest -R test_OFDM
``` 
after each change, to run the subset of OFDM tests.  Really important to keep the tests passing, before making any other changes.

**Comment by srsampson** [comment]
> Would you like me to fix `tofdm.c` or do you want to look at it?
> 
Yes, you better fix it, as I'm at a loss as to why the assert is firing off.

I'm also rebuilding an old machine to Ubuntu 18 as Ubuntu 20 won't compile the project. Just converted to 5 GHz wireless here, and added a new switch for my "lab". I've been relying on Travis to check my work, and it is a pretty slow method.

**Comment by drowe67** [comment]
> I'm also rebuilding an old machine to Ubuntu 18 as Ubuntu 20 won't compile the project. Just converted to 5 GHz wireless here, and added a new switch for my "lab". I've been relying on Travis to check my work, and it is a pretty slow method.

Ouch!  Yeah much better to have a local environment to test.  At some stage we should find out what's broken with Ubuntu 20.  A few months ago @tmiw had Travis configured to run Ubuntu 20 and IIRC it worked OK.  So we must be close.

**Comment by drowe67** [comment]
There you go @srsampson.  if you're keen, couple of suggested next steps:
1. Build up a ```qam16.c``` with ctest to mirror ```qam16.m``` and ```qam16_test.m```.  Your qam16 C functions looked pretty good :+1:  but I left them out of the debug pass above in order to focus on the bugs.
2. Modify ```ofdm_txframe``` and ```ofdm_mod``` to handle packets with multiple modem frames.  I can help you develop a ctest with one of the data modes to give that a work out, once the current ctests are passing.

Another task is to strip out the 700D interleaver from ```ofdm_mod.c```, ```ofdm_demod.c```, ```freedv_700.c``` and friends.  That's a big job, which I'll tackle in it's own PR.  No one ended up using the interleaver for 700D, it has sync problems, and greatly complicates the code.  For data the packet/modem frame design works much better - we can spread LDPC codewords across multiple modem frames to get the same result.  That's working quite well in the Octave simulations.

**Comment by tmiw** [comment]
@drowe67, actually, Travis uses Fedora from what I remember. The change was to bump up the Fedora version by 1 to get some newer libraries. Not sure how much effort it would be to go from Fedora to Ubuntu.

**Comment by hobbes1069** [comment]
No, unfortunately (as the token Fedora guy) Travis CI doesn't... It's all Ubuntu based.

**Comment by tmiw** [comment]
> No, unfortunately (as the token Fedora guy) Travis CI doesn't... It's all Ubuntu based.

Oops, I took a look again and it was Docker that uses Fedora. Carry on.

**Comment by srsampson** [comment]
The theory is, that the current functions are so tied to QPSK that I am abandoning them by renaming them for legacy use. That will allow us to develop new functions that use the "ofdm->bps" value appropriately.

**Comment by srsampson** [comment]
I made a mistake here and did a commit on my development directory, instead of the github directory.

I need to back this one out.

**Comment by srsampson** [comment]
Well darn. I was about 6 tests shy of all the tests passing with the interleave removed. But I pushed the wrong directory and gimped the whole thing up.

**Comment by drowe67** [comment]
Yes I get into this sort of trouble with Git.  I've found it helps if I make small changes, ctest-ing and committing as I go. I always have to Google how to revert changes. Was much easier in SVN.

**Comment by hobbes1069** [comment]
Yes, git is powerful but complicated. Funnily enough I just found this after reading the email:
https://devhints.io/git-tricks

**Comment by srsampson** [comment]
Since I lost all my work and will have to re-create it, I decided to make a new branch ss-interleave.

That way I can make smaller changes, instead of blowing 4-hours hee...

**Comment by drowe67** [comment]
@srsampson is it OK if I merge this?  Trying to keep the chunks of work manageable.

**Comment by srsampson** [comment]
Boy, I don't know. It's pretty experimental for merging into master.

I would rather merge the interleave one, but even that one disables some
FreeDV features (interleave) from working.

**Comment by drowe67** [comment]
> Boy, I don't know. It's pretty experimental for merging into master. I would rather merge the interleave one, but even that one disables some FreeDV features (interleave) from working.

Well freedv-gui gets built as part of the Travis tests, so we know it links OK.  Also - all the modem tests pass. Perhaps we could first build freedv-gui against this branch, and run some basic tests (like play some files through it), just to be sure.  Would you like to try that?  The freedv-gui ```build_linux.sh``` script can accept variables for different codec2 branches/hashes.

**Comment by srsampson** [comment]
Haven't done that before, but willing to give it a try!

**Comment by drowe67** [comment]
Cool :sunglasses:  At the top of the [freedv-gui user manual](https://github.com/drowe67/freedv-gui/blob/master/USER_MANUAL.md) are some instructions on playing the test files in the ```wav``` folder.

**Comment by srsampson** [comment]
Hmm.. That didn't go well. Will troubleshoot.

$~/github/freedv-gui/build_linux$ freedv
freedv: symbol lookup error: freedv: undefined symbol: freedv_open_advanced

**Comment by srsampson** [comment]
Disregard. Had to rebuild library for codec2 and install in /usr/local/lib

**Comment by srsampson** [comment]
OK, worked as normal on test waveform. I tried switching the interleave
(all the way to 16) and it copied just the same, so of course the buffer
interleave was non-functional.

My opinion is it can be merged.

**Comment by srsampson** [comment]
P.S. also tried other modes. No problems.

**Comment by srsampson** [comment]
oops, forgot mode 2020. It blows-up.

tart .....
freedv: /home/ssampson/codec2/src/ofdm.c:1576: ofdm_set_sync: Assertion
`ofdm != NULL' failed.
Aborted (core dumped)

**Comment by drowe67** [comment]
> Disregard. Had to rebuild library for codec2 and install in /usr/local/lib

The `build_linux.sh` script clones a local copy of codec2.  You can set that local codec2 repo to any branch/hash you like, and even edit/build in there and push any changes you need.  So you shouldn't have to `make install` - indeed it might lead to trouble as freedv-gui is built against the local codec2.

Looking at yr code I figure it's very close to working with freedv-gui/master.  But if you get stuck testing with freedv-gui just let me know and I'll take a look at it some time, before we merge this PR.

**Comment by srsampson** [comment]
P.S. I've been building against the ss-interleave branch. Not this one.

I think the best way forward is to manually merge the changes here into ss-interleave and delete this one. I believe this one has some ofdm_mod and demod changes and ofdm changes but not much else.

**Comment by srsampson** [comment]
I think I am going to close this one. It looks like all the changes here were incorporated in ss-interleave.

I know that was a side line project not really associated with the new modem stuff, but did include the changes here. Some of the changes here were backed-out in one of your changes, so they have to be added back in when I re-read the Octave code.

**Comment by srsampson** [comment]
Closed this one in favor of ss-interleave branch

**Comment by drowe67** [comment]
@srsampson would you mind if I re-open this PR? I'd like to review the ofdm.c modem changes in isolation from the interleaver changes in https://github.com/drowe67/codec2/pull/138.  It won't affect your work in https://github.com/drowe67/codec2/pull/138, which (I think) was branched off this PR anyway.

**Comment by srsampson** [comment]
Feel free!

**Comment by drowe67** [comment]
Hi @srsampson - this works just fine with freedv-gui.  I tested both 700D and 2020 Rx using the demo wav files.  Passes all the ctests so all good to merge.  I'll merge this one, which will make https://github.com/drowe67/codec2/pull/138 easier to review.

Nice work :+1:

**Pull request merged**
