### PR TITLE
CMakeLists fixup for check_symbols_exist

### PR DESCRIPTION
**Pull request by hobbes1069**
Fix linking with math library for check_symbols_exists and correct getopt header.

### CODE REVIEW

**Comment by drowe67** [comment]
Thanks @hobbes1069.  So this issue was particular to Fedora 30?  I haven't seen anything sim8lar on the various flavours of Ubuntu I use.

**Comment by hobbes1069** [comment]
I guess so, I don't have another system to compare to. Perhaps the math library is implied on other systems? I may have to bootup Ubuntu in my VM and see. I'm not sure if I can dig into Travis CI enough to get the details.

**Comment by drowe67** [comment]
Yep, builds fine on all Ubuntus I have tried.

**Comment by hobbes1069** [comment]
Well it still built fine for me but configuration complained because the check_symbols_exists was not linking with the math library, however, that would affect all the "HAVE_<X>" definitions and I have no idea what differences in the resultant binaries there would be due to that.

**Comment by drowe67** [comment]
All the tests run on Travis pass fine https://travis-ci.com/drowe67/codec2/builds/129861987, so I don't think there is a problem on Ubuntu.

**Comment by drowe67** [comment]
@hobbes1069 just let me know when your OK with the Fedora 30 side and I'll merge.

**Comment by hobbes1069** [comment]
This can get merged regardless but it looks like the problem with at least some of the tests is it assumes the build directory is in a subdirectory of the source... I create a build directory completely outside of the git directory. I'll what it'll take to use cmake variables so that won't matter.

Also, what is "pkg load signal"?

**Comment by hogthrob** [comment]
https://octave.org/doc/v4.0.1/Using-Packages.html

**Comment by drowe67** [comment]
"pkg load signal" is an Octave command to load the signal processing package (library), used to support some tests.

**Comment by hobbes1069** [comment]
Guess I need to install octave then :)

**Comment by hobbes1069** [comment]
Let's go ahead and merge this. I'll add a new PR to fix the tests. I'm probably going to have to move the shell files to a .in file and substitute in the correct path based on the build directory.

**Pull request merged**
