### PR TITLE
Donmr stm32

### PR DESCRIPTION
**Pull request by donmr**
Small changes to stm32 tests, and ofdm.c to eliminate warnings found be Arm compiler.

Add a .gitignore file

### CODE REVIEW

**Comment by srsampson** [comment]
The (double) cast was removed by me by accident. For some reason I haven't been getting a compiler warning on that. 

I generally don't initialize arrays if the code itself fills all indexes. Actually, I think, symbol[] here should be moved inside the "if (ofdm_high_doppler == 0) {" block, as it is no longer used in high doppler block.

Being a Java programmer, I never use "unsigned" and most C style guides deprecate it for anything outside of bit-twiddling. The reason being the compilers themselves pick the loop variable size, and may punt into the stands if you use "unsigned".

**Comment by donmr** [comment]
The compiler was giving warnings for symbol possibly not initialized and 
for I,j,k computations not working with negative values.  My changes were 
to eliminate them.  Since the array is so small I don't think initializing 
it will slow things down.

Don

**Comment by srsampson** [comment]
```
for I,j,k computations not working with negative values
```
I better take a look at that. We definitely shouldn't have negative values (I don't think). I'll insert a couple of assert() statements and test.

**Comment by donmr** [comment]
We won't have negative, I'm pretty sure, but the code is too complex for 
the compiler to know that.  Working with unsigneds is just as as fast...

Don

**Comment by db4ple** [comment]
Hi,
if we replace 
            `for (j = (i - 1), k = 0; j < (i + 2); j++, k++)`
with the functional equivalent
            `for (k = 0, j = (i - 1); k < 3 ; k++, j++)`
the compiler knows it will always initialize before using so the init loop can be removed.
I also agree to move it inside the "if" is a good idea. This, by the way will also make the move to unsigned no more required (does not harm either).

> I generally don't initialize arrays if the code itself fills all indexes. Actually, I think, symbol[] here should be moved inside the "if (ofdm_high_doppler == 0) {" block, as it is no longer used in high doppler block.
> 
> Being a Java programmer, I never use "unsigned" and most C style guides deprecate it for anything outside of bit-twiddling. The reason being the compilers themselves pick the loop variable size, and may punt into the stands if you use "unsigned".

**Comment by srsampson** [comment]
Aha... Good fix!

**Comment by srsampson** [comment]
I just looked, and there are about 15 places or so where this can be done (first part =0). I can change them after your fixes are imported.

**Comment by donmr** [comment]
I backed out my changes to ofdm.c.  If you want I can create an issue for the warnings for you to fix (although I think you know what they are at this point).  In the future I'll do that for other developer's files.

**Comment by srsampson** [comment]
Yes, I'll put together a change this evening, and post it. Thanks!

**Comment by db4ple** [comment]
@donmr @drowe67 
Will this be merged soon? I have a couple of additional changes waiting, which I would like to put into a pull request, but these are based on this pull request being applied. I can change that dependency but don't want to break this pull request.

**Comment by drowe67** [comment]
> @donmr @drowe67
> Will this be merged soon? I have a couple of additional changes waiting, which I would like to put into a pull request, but these are based on this pull request being applied. I can change that dependency but don't want to break this pull request.

Reading above, sounds like Steve wanted to do a little more work?  I'm OK with it being merged whenever @donmr and @srsampson are.

**Comment by srsampson** [comment]
No problems for me on merge.

**Comment by donmr** [comment]
Yes, please merge what is left of that PR.

Thanks
Don

**Pull request merged**
