### PR TITLE
TTY for SM1000

### PR DESCRIPTION
**Pull request by drowe67**
Trying to build a simple. low memory way to printf debug messages (such as memory used) from the SM1000.  A USB comm port would be idea, and we have source for that, but I am concerned about run time memory usage.

### CODE REVIEW

**Comment by drowe67** [comment]
@donmr I have a basic unit test compiling but not tested yet.  Feel free to work on this if it is of any interest (you may have other plans for SM1000 debug tools).  I'll move it forward over the next few weeks.

**Comment by donmr** [comment]
A simple puts that is mostly called with strings from the ROM and a form of 
itoa can do a lot with just a few bytes of static memory.

Don

**Comment by drowe67** [comment]
> A simple puts that is mostly called with strings from the ROM and a form of itoa can do a lot with just a few bytes of static memory. Don

Exactly - so we could have it 'counting down" the available stack and heap as the various modules come up.  Add a sentinel to the end of stack/heap and monitor that.

**Comment by drowe67** [comment]
@db4ple I have the basic unit testing going but my baud rate is 3030 rather than 9600. I think #define HSE is set to 25MHz rather than 8MHz when the STM library is built.  Might be able to set this at build time.

**Comment by db4ple** [comment]
@drowe67 

Found an interesting piece of code:

https://github.com/drowe67/codec2/blob/5866cb46ec844dfa3178156bdbddd53b5abda757/stm32/inc/stm32f4xx_conf.h#L26-L30

This set the HSE_VALUE to 80000000 if and only if someone set the HSE_VALUE to something.
If HSE_VALUE is not set, it will define nothing and we get the default 25 Mhz....
In a nutshell: if we define HSE_VALUE (regardless of the value), we will assume 8 Mhz clock. If not, we assume 25Mhz clock.
That does not make sense.
Either, 
1. we use 8 Mhz if nothing is defined and the defined value if HSE_VALUE is set, OR
2. we use 8 Mhz all the time.

But the current code is stupid. I vote for 1.

```c
#if !defined  (HSE_VALUE)
  /* Define the HSE value; it's equal to 8 MHz on the STM32F4-DISCOVERY Kit */
 #define HSE_VALUE    ((uint32_t)8000000)
#endif /* !HSE_VALUE */

**Comment by drowe67** [comment]
Good catch. 

However I'm not sure if https://github.com/drowe67/codec2/blob/5866cb46ec844dfa3178156bdbddd53b5abda757/stm32/inc/stm32f4xx_conf.h#L26-L30 is included when we build the stm peripheral lib.  The USART functions are deep inside the peripheral lib, and call RCC_ functions that need the compiler time value of HSE_VALUE.

I've just pushed a fix to this PR, see what you think.

**Comment by db4ple** [comment]
Well, this should work in any case due to the nature of the problem: if inc/stm32f4xx_conf.h is used, it will define 8Mhz clock since you set the HSE_VALUE. If not, the define HSE_VALUE will do the intended job.

**Comment by db4ple** [comment]
HSE_VALUE is only used in the https://github.com/drowe67/codec2/blob/5866cb46ec844dfa3178156bdbddd53b5abda757/stm32/src/system_stm32f4xx.c
(and in the usb_vcp_ut.c) but not in the StdPeriphlib directly. The mentioned file has the code to initialize the STM32 clocks.

**Comment by drowe67** [comment]
@donmr @db4ple I have a small usart library working now, which can do things like usart_puts("Hello World\n").  it's running on bear atm, just login and ```sudo tio -m INLCRNL /dev/ttyUSB0```. Feel free to modify the program with openocd/gdb if you like.

@db4ple - I found a stm32 peripheral library example ```USART_printf``` where they could redirect the printf output to a custom puts() function, but couldn't get it to work.  I imagine the default is weakly linked.  I'd be happy to try this approach again if you have any thoughts on how to get it working.

**Comment by drowe67** [comment]
@donmr and @db4ple if you think this is OK lets merge it.

**Comment by donmr** [comment]
I like it, it's working on an SM1000 board.   There is something that is changing the first byte after a boot to 0xFF but later output is fine.

**Pull request merged**
