### PR TITLE
Added c2server

### PR DESCRIPTION
**Pull request by ea3ihi**
c2server implements a simple udp socket server to encode/decode PCM to/from codec2 2400 bps.

The 6 bytes (48 bits) codec2 data is suffixed with another byte with the value 0xC2. 

c2server can substitute md380-emu, for instance used along dvswitch or DMRStation. This can be a very first step to have a proper open source codec in DMR radio.

The extra byte (0xC2) could serve as a tag to identify codec2 encoded audio in DMR environments.

### CODE REVIEW

**Comment by drowe67** [comment]
Hello @ea3ihi - thank you for the PR.  This looks interesting.  Couple of questions:
1. Is this something that should be in codec2, or perhaps be a stand alone application that uses libcodec2?
1. If you are keen to have it merged with codec2, lets talk about a ctest that exercises it, and some documentation (perhaps at the top of the C source file) showing example use.

**Comment by ea3ihi** [comment]
Hello @drowe67 having the server built along  codec2 will make it really easy for radio amateurs to obtain it and get it running, let me know what you think.

I will add some ussage instructions to the c file. Regarding the tests maybe a simple shell script that uses nc to interact with the udp server is enough?, or should I create a simple application for testing?

**Comment by drowe67** [comment]
@ea3ihi is anyone using this program at the moment?  Being an application, I'm wondering if it is better kept in your own repo, rather than as part of the codec2 repo?

**Comment by ea3ihi** [comment]
Yes, maybe it is better to keep it in my own repo for now

**Comment by drowe67** [comment]
@ea3ihi but it is a fine idea, please feel free to present it and discuss it on the [codec 2 list](https://sourceforge.net/projects/freetel/lists/freetel-codec2) :smile:

**Comment by ea3ihi** [comment]
I will do

Regards,

David

**Pull request closed without merging**
