### PR TITLE
Added cmake builds for stm32/unittest/src

### PR DESCRIPTION
**Pull request by db4ple**
This is an attempt to replicate the existing stm32/unittest Makefile
It is missing the code generation part of the existing makefile

### CODE REVIEW

**Comment by drowe67** [comment]
@db4ple OK - so is this extending the cmake build system to @donmr's unit tests?

**Comment by db4ple** [comment]
Yes, exactly. It works for the moment in parallel with the makefile. There is no interference between both, since the cmake build is in a separate directory outside the source tree.
@donmr : It would be cool, if you could verify that the cmake built binaries are working as expected.
@hobbes1069 : Any guidance from your side related to make good use of cmake's capabilities is appreciated.

**Comment by hobbes1069** [comment]
Looks pretty good and clean. Should we add a conditional around the add_subdirectory and an option for either enabling or disabling unittesting? Or should we assume anyone messing with stm32 should be building and using the testing? 

One thing I haven't really touched before is CMake's testing module CTest. Do we want to do any automated testing during building?

**Comment by donmr** [comment]
I pulled the latest files and tried to run cmake in the stm32 directory.

With a copy of the library in the build directory, per the README file,
it complains that it cannot find library files:

-------------------------------------------------------------------------------
build_stm32 $ cmake .. -DCMAKE_TOOLCHAIN_FILE=../cmake/STM32_Toolchain.cmake 
-- We are cross compiling...
-- CMAKE_C_FLAGS: -specs=nosys.specs -Wall -std=gnu11 -mlittle-endian -mthumb -mthumb-interwork -nostartfiles -mcpu=cortex-m4 -Wall -std=gnu11 -mlittle-endian -mthumb -mthumb-interwork -nostartfiles -mcpu=cortex-m4 -fsingle-precision-constant -Wdouble-promotion -mfpu=fpv4-sp-d16 -mfloat-abi=hard -D__FPU_PRESENT=1 -D__FPU_USED=1
-- CMAKE_ASM_FLAGS: -specs=nosys.specs -Wall -std=gnu11 -mlittle-endian -mthumb -mthumb-interwork -nostartfiles -mcpu=cortex-m4 -Wall -std=gnu11 -mlittle-endian -mthumb -mthumb-interwork -nostartfiles -mcpu=cortex-m4 -fsingle-precision-constant -Wdouble-promotion -mfpu=fpv4-sp-d16 -mfloat-abi=hard -D__FPU_PRESENT=1 -D__FPU_USED=1 -x assembler-with-cpp
-- Configuring done
CMake Error at cmake/STM32_Lib.cmake:342 (add_library):
  Cannot find source file:

    /home/don/Radio/Digital/FreeDV/Source/Git/codec2/stm32/STM32F4xx_DSP_StdPeriph_Lib_V1.8.0/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_f32.c
...
-------------------------------------------------------------------------------

That file is there:

-------------------------------------------------------------------------------
build_stm32 $ ls STM32F4xx_DSP_StdPeriph_Lib_V1.8.0/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_f32.c
STM32F4xx_DSP_StdPeriph_Lib_V1.8.0/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_f32.c
-------------------------------------------------------------------------------

Don

**Comment by db4ple** [comment]
Yes, I should have mentioned that. It seems the library should be placed inside the stm32 directory. I did that in my .travis.yml as well. So cmake instructions are not correct (or the cmake script). We should fix that.

**Comment by db4ple** [comment]
Well, instructions are wrong. Looking into stm32/STM32_Lib.cmake tells us that a few things are hardcoded there (library version and library source location inside the source dir).

**Comment by db4ple** [comment]
I added an option to set the PERIPHLIBDIR explicitly and adjusted .travis.yml and the README.cmake accordingly. My travis build including the STM32 build (not the one here which skips it) shows it works as expected.

**Comment by donmr** [comment]
These stm32 CMake changes are apparently not in the main codec2 repository,
they are in db4ple's forked one.  I'm not very practiced yet at how to
handle that without messing something up.  So it may take a while for me
to test it.

Don

**Comment by db4ple** [comment]
@donmr  
No, these changes are only a pull request (yet). 
If you want direct access to my repository, just add it as remote (repository) e.g. under remote name db4ple. 
Then you can simply check out one of my branches, e.g. my master branch:  `git fetch db4ple; git checkout db4ple/master`.  

You cannot directly commit to this branch but it should be sufficient for testing stuff.

Otherwise you can also pull / rebase one of your branches to my branch and then make changes and commit them.

**Comment by drowe67** [comment]
@db4ple @donmr .... as someone who has just coming up to speed on Git in the last 6 months ... it's a powerful, but complex piece of software with many traps for those climbing the learning curve.  I'm sensitive to developers becoming bogged down with learning the "tools" rather than doing the work.

Danilo - one possibly simpler way is put yr work in a branch in this repo. That way Don just has to:
```
$ cd codec2
$ git pull
$ git checkout danillos-branch
```
and he can also commit to the repo if needed, sharing development with you.....

**Comment by db4ple** [comment]
I just created the cmakestm32 branch in this repo, with the same content as used to create this pull request.

Still, the commands depend on the exact configuration of one's local git repo.
For me it would not work, since I have my  GitHub fork as the default remote repositry for my local branches and "drowe67" points to the original repo here. In this case `git pull` would not fetch the content of "drowe67". I have to use `git fetch drowe67` and to checkout I have to use
`git checkout -b cmakestm32 --track drowe67/cmakestm32; git pull --rebase`  (please note that the local branch may have a completely different name).

**Comment by donmr** [comment]
OK, I have pulled it and tried.  I ran into a small issue I have also seen
with the old Makefile system.


src/codec2.h includes <codec2/version.h> (at line 36).

This file is not in the source, it gets created when codec2 is built.
I have it in 

	codec2/build_linux/codec2/version.h

and also in

	codec2/stm32/build_stm32/codec2/version.h

There is something in stm32/CMakeLists.txt that looks like it is trying
to find this, but it apparently is not working. 

-------------------------------------------------------------------------------
cmake .. -DCMAKE_TOOLCHAIN_FILE=../cmake/STM32_Toolchain.cmake
...
make
...
Scanning dependencies of target tst_codec2_fft_init
[ 91%] Building C object unittest/src/CMakeFiles/tst_codec2_fft_init.dir/tst_codec2_fft_init.c.obj
In file included from /home/don/Radio/Digital/FreeDV/Source/Git/codec2/stm32/unittest/src/tst_codec2_fft_init.c:33:0:
/home/don/Radio/Digital/FreeDV/Source/Git/codec2/stm32/../src/codec2.h:36:10: fatal error: codec2/version.h: No such file or directory
 #include <codec2/version.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
unittest/src/CMakeFiles/tst_codec2_fft_init.dir/build.make:62: recipe for target 'unittest/src/CMakeFiles/tst_codec2_fft_init.dir/tst_codec2_fft_init.c.obj' failed
make[2]: *** [unittest/src/CMakeFiles/tst_codec2_fft_init.dir/tst_codec2_fft_init.c.obj] Error 1
CMakeFiles/Makefile2:1237: recipe for target 'unittest/src/CMakeFiles/tst_codec2_fft_init.dir/all' failed
make[1]: *** [unittest/src/CMakeFiles/tst_codec2_fft_init.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
-------------------------------------------------------------------------------

Don

**Comment by hobbes1069** [comment]
> These stm32 CMake changes are apparently not in the main codec2 repository, they are in db4ple's forked one. I'm not very practiced yet at how to handle that without messing something up. So it may take a while for me to test it. Don
> […](#)
(https://github.com/drowe67/codec2/pull/4#issuecomment-475940797)

Don, You can also try creating a patch from the pull request but adding .patch to the URL and apply it to a local copy...
[stm32]$ patch -p1 < 4.patch

I might do it on a copy of a checkout...

**Comment by hobbes1069** [comment]
As far as codec2/version.h is this an area where we need to be more disiplined about reaching into codec2 code? I know they're tightly coupled.

Another option is to create our own codec2/version.h in the build directory just to satisfy the build...

**Comment by db4ple** [comment]
Hi,
codec2/version.h is included from codec2.c, that is why it is needed. However, it is generated by cmake for the stm32 CMakeLists.txt and this works just fine for me. I don't know why this doesn't work for Don.

**Comment by hobbes1069** [comment]
Ok, I thought I had fixed that but slept too many times since then :)

**Comment by db4ple** [comment]
Richard,
well, your fix seems to work at least for me.

**Comment by donmr** [comment]
That looks like a change to travis.xml, but not the the CMake files.

I need to be able to compile one or more programs in my workspace
without running the whole test suite.

The version file is getting created in stm32/build_stm32/codec2/version.h
but for some reason it is not found.

I am running cmake in a build directory below stm32.  That seems to be
required as the unittest CMakeLists.txt will not run by itself, which is OK.

Don

**Comment by db4ple** [comment]
Don, could you try to run the cmake call outside the normal source tree (anywhere outside the  codec2 directory structure). This is how I do this and it has no trouble with codec2/version.h 

You can compile any specific program by just saying "make <program>"

**Comment by db4ple** [comment]
Don, I checked, and even building inside stm32/build_stm32 with cmake works without problems for me.
I assume you completely cleaned out the build_stm32 directory? If not, please try that and rerun the recommended cmake call (see README.cmake)

**Comment by db4ple** [comment]
I am sorry, I should have waited until the very end of the cmake build...
No, it does not work. Unless we make a change. Which I did now.

**Comment by drowe67** [comment]
Nice work @db4ple.  When you are all happy with this PR pls let me know and I'll merge.

**Comment by donmr** [comment]
I had to update a couple of test scrpts.  You can merge them too, or I can submit a requesr, or I can merge them???

**Comment by db4ple** [comment]
I guess easiest would be you create a new pull request including my AND your changes:
David merges the new PR into master and closes this PR without merging it.

However, I can't see that you made your own fork of the repository. So I assume you made the changes in your local branch which has drowe67/cmakestm32 as remote tracking branch. In this case you have to 
commit your changes and push your local branch into the drowe67 repository and create the pull request based on this branch. If you need help with git, let us know. Can be a little overwhelming at first (and later as well).

**Comment by donmr** [comment]
Ah yes add, then commit, then push.  Git has so many levels :-)

I pushed the changes to the server.

Don

**Comment by db4ple** [comment]
Obsoleted by #7

**Comment by drowe67** [comment]
@donmr yes it's a bit more complicated for sure, although having a local repo can be handy sometimes. I often use the short cut ```git commit -a -m "comment"``` to commit all changed files without an explicit ```git add```, also ```git status -uno``` tells you what's changed, ignoring the untracked files.

**Comment by donmr** [comment]
Yes, I know what the commands are but don't always remember to do them
all.  Your example below does a commit but not a push.

That brings up another question.  Do you want me to push changes
directly into the master, or into a branch and then have you pull them?

I suggest that "simple" changes to the stm32 tests and the sm1000 code
should be pushed directly while more complex changes or changes to other
code should probably use a branch.

Don

**Comment by drowe67** [comment]
Hi Don - Pls do your work in your own branch/pull request, and ask me to merge when ready.  If they are simple changes then accumulate them over time and we can merge periodically. This way while you are developing your work won't be affected by other people changing code at the same time - a problem that was starting to become common with SVN and one of the reasons we moved to Git.  Come merge time any incompatibilities can be dealt with all at once.

**Comment by db4ple** [comment]
I agree with David, nothing should be "developed" in the GitHub master branch and there should be no direct push to this branch.
 
Maybe we have a look at the workflow we have been using for a while now with the UHSDR firmware.
Basically we require there the commits to be done through pull request and to be based on the newest commit of the master branch. This is achieved by using `git rebase` frequently in ones "local" branch even during development and latest before making the pull request.

That approach works best if a single person works on a (set of) changes locally and then pushes the results into a separate GitHub branch. One should never push a rebased  branch into the  Github's master repositories "master" branch as this will create a mess many will not be able to get out from.

**Pull request closed without merging**
