### PR TITLE
Clean up warnings when using -Wall

### LINKED ISSUE #202: Warnings discovered with -Wall
Note below. This is with clang on macOS so it may be different on other platforms:

```
[ 14%] Building C object src/CMakeFiles/codec2.dir/codebooknewamp2.c.o
/Users/mooneer/devel/freedv-gui/codec2/build_osx/src/codebooknewamp2.c:522:5: warning: implicit conversion from 'double' to 'int' changes value from 8.965780000000001 to 8 [-Wliteral-conversion]
    8.96578,
    ^~~~~~~
1 warning generated.
/Users/mooneer/devel/freedv-gui/codec2/build_osx/src/codebooknewamp2.c:522:5: warning: implicit conversion from 'double' to 'int' changes value from 8.965780000000001 to 8 [-Wliteral-conversion]
    8.96578,
    ^~~~~~~
1 warning generated.

...

[ 73%] Building C object unittest/CMakeFiles/compare_ints.dir/compare_ints.c.o
/Users/mooneer/devel/freedv-gui/codec2/unittest/compare_ints.c:129:43: warning: format specifies type 'long' but the argument has type 'int64_t' (aka 'long long') [-Wformat]
            printf("%d %ld %ld\n", count, data1, data2);
                       ~~~                ^~~~~
                       %lld
/Users/mooneer/devel/freedv-gui/codec2/unittest/compare_ints.c:129:50: warning: format specifies type 'long' but the argument has type 'int64_t' (aka 'long long') [-Wformat]
            printf("%d %ld %ld\n", count, data1, data2);
                           ~~~                   ^~~~~
                           %lld
2 warnings generated.
/Users/mooneer/devel/freedv-gui/codec2/unittest/compare_ints.c:129:43: warning: format specifies type 'long' but the argument has type 'int64_t' (aka 'long long') [-Wformat]
            printf("%d %ld %ld\n", count, data1, data2);
                       ~~~                ^~~~~
                       %lld
/Users/mooneer/devel/freedv-gui/codec2/unittest/compare_ints.c:129:50: warning: format specifies type 'long' but the argument has type 'int64_t' (aka 'long long') [-Wformat]
            printf("%d %ld %ld\n", count, data1, data2);
                           ~~~                   ^~~~~
                           %lld
2 warnings generated.

...

[ 83%] Building C object unittest/CMakeFiles/ofdm_stack.dir/ofdm_stack.c.o
clang: warning: argument unused during compilation: '-no-pie' [-Wunused-command-line-argument]
[ 84%] Building C object unittest/CMakeFiles/ofdm_stack.dir/__/src/ofdm.c.o
clang: warning: argument unused during compilation: '-no-pie' [-Wunused-command-line-argument]
[ 84%] Building C object unittest/CMakeFiles/ofdm_stack.dir/__/src/octave.c.o
clang: warning: argument unused during compilation: '-no-pie' [-Wunused-command-line-argument]
[ 84%] Building C object unittest/CMakeFiles/ofdm_stack.dir/__/src/kiss_fft.c.o
clang: warning: argument unused during compilation: '-no-pie' [-Wunused-command-line-argument]
[ 85%] Building C object unittest/CMakeFiles/ofdm_stack.dir/__/src/modem_probe.c.o
clang: warning: argument unused during compilation: '-no-pie' [-Wunused-command-line-argument]
[ 85%] Building C object unittest/CMakeFiles/ofdm_stack.dir/__/src/mpdecode_core.c.o
clang: warning: argument unused during compilation: '-no-pie' [-Wunused-command-line-argument]
[ 85%] Building C object unittest/CMakeFiles/ofdm_stack.dir/__/src/phi0.c.o
clang: warning: argument unused during compilation: '-no-pie' [-Wunused-command-line-argument]
[ 86%] Building C object unittest/CMakeFiles/ofdm_stack.dir/__/src/filter.c.o
clang: warning: argument unused during compilation: '-no-pie' [-Wunused-command-line-argument]
[ 86%] Linking C executable ofdm_stack
clang: warning: argument unused during compilation: '-no-pie' [-Wunused-command-line-argument]
```

Other than codebooknewamp2.c, they seem straightforward. Any reason why lsp_codebook is defining that particular field as int?

### PR DESCRIPTION
**Pull request by tmiw**
Cleans up warnings when using -Wall to compile Codec2. Resolves #202.

### CODE REVIEW

**Comment by srsampson** [comment]
I'm wondering is ceilf() would be better. That is, any resulting fraction being raised to the next integer value?

**Comment by tmiw** [comment]
> I'm wondering is ceilf() would be better. That is, any resulting fraction being raised to the next integer value?

Actually, perhaps it should be truncated. That's what the implicit cast has been doing, right?

**Comment by srsampson** [comment]
> > I'm wondering is ceilf() would be better. That is, any resulting fraction being raised to the next integer value?
> 
> Actually, perhaps it should be truncated. That's what the implicit cast has been doing, right?

1. I think that was a bug, because 2^8 wouldn't address all 500 values.

2. I wonder if the quality of codec 450 is better with m = 500 log2(m) = 9

**Comment by srsampson** [comment]
2a. Hmm... It doesn't appear to make any difference in 450 audio. The two raw files were identical.

**Comment by tmiw** [comment]
Maybe we should rerun unit tests just to be sure other modes aren't affected?

**Comment by srsampson** [comment]
> Maybe we should rerun unit tests just to be sure other modes aren't affected?

FYI - I created a build with just the one roundf() change, and all the tests passed.

**Comment by tmiw** [comment]
> FYI - I created a build with just the one roundf() change, and all the tests passed.

Sounds good.

@drowe67, does this PR seem reasonable for merge?

**Comment by drowe67** [comment]
@tmiw and @srsampson - thanks.  I'm a little busy atm so will look at this one over the next week or so.  I'd like to merge it after we have a codec 1.0 release.

**Pull request merged**
