### PR TITLE
tst_api_mod failing

### PR DESCRIPTION
**Pull request by donmr**
I tracked this part way.

First the run_stm32_prog script needs to be fixed to allow the --debug option to work again.

The test itself is not yet working though.  This version calls abort() inside newamp1/rate_K_mbest_encode().

I am out of time this morning to work on it.

### CODE REVIEW

**Comment by drowe67** [comment]
I've traced it to an out of memory issue in one of the mallocs on ofdm_create, which wasn't being trapped by freedv_open().  Haven't go to the root cause yet, maybe some work I did to get 700D working again for x86 platforms.

Have emailed @srsampson re using asserts in ofdm_create().

@donmr I've also got the test system printing stuff to the console (as well as log files), and giving useful assert() ouput:
```
-----------------------------
    STARTING gdb/OpenOCD     
-----------------------------
Open On-Chip Debugger 0.10.0+dev-00796-ga4ac5615 (2019-04-21-17:47)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Info : The selected transport took over low-level target control. The results might differ compared 
<snip>
----------------------------STARTING PROGRAM-------------------------
Note: automatically using hardware breakpoints for read-only addresses.
assertion "ofdm->rxbuf != NULL" failed: file "/home/david/codec2/src/ofdm.c", line 265, function: ofdm_create

```
will clean up and post the tweaks I made for your review.

**Comment by donmr** [comment]
Great.

This weekend is the big US "Field Day" so I'll be busy with that.

Don

**Comment by drowe67** [comment]
OK I found the problem!  My recent adventures in Codec 2 700C VQ .... I'd made the VQ tables regular floats (not const) so I could load them at run time, so they ended up in data memory ... all 80k!  So ofdm_create couldn't find enough heap.  

test passes if I relaxed the tolerance to 4 (2 bits) on codec data which is reasonable (you would never hear that difference on 16 bit samples).

Also found some error conditions (like ofdm_create() returning NULL) that we weren't checking, and a good exercise to get my head around Don's fine test framework.

Will clean up and check in shortly.

I'd like to add some ctests to trap similar mistakes in future.  For example have tests run by Travis on the stm32 compiler map file output to make sure we aren't chewing up too much memory on stm32 systems.

**Comment by drowe67** [comment]
@donmr oops I somehow merged some of the new ofdm sync stuff as well.  You just need to review the stm232 test system changes!  Happy to revert anything you're not comfortable with.

I've added a test ```check_ram_limit``` that checks for the amount of RAM used against a threshold.  This works by looking at .map files so can run on Travis without needing stm32 hardware.  That way if I add too much to RAM again, it will be caught.

**Comment by drowe67** [comment]
I've had a go at removing the ofdm sync noise from this PR in https://github.com/drowe67/codec2/pull/46

I'm Git challenged.

**Comment by donmr** [comment]
I rebased this branch from master before I realized that you had not yet pulled in my simple change to run_stm32_prog .  Now it show a long list of changes from that.

Is there a better way for me to do this.  I could delete this branch and make a new one but that get cumbersome.  Although I think it may be needed this time.

**Comment by db4ple** [comment]
Well, you can get back your original branch before rebase, assuming you did not run any git cleanups:

`git reflog` 

You checkout the commit which was your former HEAD of the old branch and create a new branch from it `git branch abc ; git checkout abc`

**Comment by donmr** [comment]
Closing this one, this branch is too messed up.  I created a different branch and will make a new PR for the simple changes to one file.

**Pull request closed without merging**
