### PR TITLE
Steve's cohpsk refactoring

### PR DESCRIPTION
**Pull request by drowe67**
Steve's doing some re factoring of the cohpsk modem Octave code

### CODE REVIEW

**Comment by drowe67** [comment]
Very nice @srsampson.  Could you also add a few notes to the README_cohpsk.m?  Stuff like:
1. list of the files, with a sentence of each
1. examples of running
1. How to run the CTests relevant to cohpsk

**Comment by srsampson** [comment]
> Very nice @srsampson. Could you also add a few notes to the README_cohpsk.m? Stuff like:
> 
> 1. list of the files, with a sentence of each
> 2. examples of running
> 3. How to run the CTests relevant to cohpsk

Yes, early days yet.

**Comment by drowe67** [comment]
Hi @srsampson is this PR ready for merge?

**Comment by srsampson** [comment]
I think you could merge it, and everything would be alright.

I have not moved to the meat of the changes though. Feel free to merge it,
and then I will start from there.

**Pull request merged**
