### PR TITLE
cohpsk modem maintenance

### PR DESCRIPTION
**Pull request by drowe67**
Mike Riley has pointed out that this modem, as used for FreeDV 700C, appears to have applications for high Doppler rate channels.  So Steve and David are doing a little maintenance:

1. Making sure the scripts run.
1. Replacing the stored-file-based HF channel simulation with on the fly doppler spread generation like ofdm.
1. Creating Ctests for AWGN and Octave<->C port.
1. Write a README_cohpsk with some examples.

### CODE REVIEW

**Comment by srsampson** [comment]
Aha! Very good. I didn't think to compare operands. Quite an obtuse error message.

**Comment by drowe67** [comment]
OK I've managed to reproduce similar results to Mike's in simulation:
```
cd ~/codec2/build_linux
git checkout cohpsk-maintenance
git pull
make
cd src
build_linux/src$ ./cohpsk_get_test_bits - 5600 | ./cohpsk_mod - -  | ./cohpsk_ch - - -40 -f -20 | ./cohpsk_demod - - -o cohpsk_demod.txt | ./cohpsk_put_test_bits -~
```
Then, in another shell:
```
$ cd codec2/octave
$ octave --no-gui
octave> cohpsk_demod_plot("../build_linux/src/cohpsk_demod.txt")
```

Note the off results in Figure 3 __sync ratio__.  However the scatter looks good.  It's pretty sensitive to the frequency offset, not sure why.

**Comment by srsampson** [comment]
Minor: change to
```
cmake ..
make
```

**Comment by drowe67** [comment]
@srsampson Would it be OK if I broke out tcohpsk.m into two scripts so we can setup a Ctest for checking teh C<->Octave port?  Of if you have started this, I'm happy to leave it to you.

I'd like to get positioned to build a new Windows release with the freq offset bug fix, and checking out the C<->Octave port is the first step.

**Comment by srsampson** [comment]
> @srsampson Would it be OK if I broke out tcohpsk.m into two scripts so we can setup a Ctest for checking teh C<->Octave port? Of if you have started this, I'm happy to leave it to you.
> 
> I'd like to get positioned to build a new Windows release with the freq offset bug fix, and checking out the C<->Octave port is the first step.

Yes, feel free. I will reorient with your changes.

**Comment by drowe67** [comment]
@donmr and @db4ple is this PR OK from a stm32 point of view?  It's mainly to do with the cohpsk modem but thought I better check just in case. I have messed with .travis.yml a bit.

I apologise for adding the rather slow (60s) tcohpsk test, I cut it back as far as I dared (just 30 frames now from original 100).  Several bugs crept into this modem that were affecting the UK FreeDV users so I wanted to back it up with some tests.

**Comment by db4ple** [comment]
Docker Ubuntu 16.04 against PR#17:
```
GIT_REPO=https://github.com/drowe67/codec2.git
GIT_REF=+refs/pull/17/merge
 1/15 Test  #1: test_FDMDV_modem_octave_port ...................   Passed   17.71 sec
 2/15 Test  #2: test_COHPSK_modem_octave_port ..................***Failed  Required regular expression not found.Regex=[fails: 0
 3/15 Test  #3: test_OFDM_modem_octave_port ....................   Passed   20.44 sec
 4/15 Test  #4: test_OFDM_modem_octave_port_Nc_31 ..............   Passed   22.27 sec
 5/15 Test  #5: test_COHPSK_modem_AWGN_BER .....................   Passed    0.17 sec
 6/15 Test  #6: test_COHPSK_modem_freq_offset ..................   Passed    0.17 sec
 7/15 Test  #7: test_OFDM_modem_AWGN_BER .......................   Passed    1.70 sec
 8/15 Test  #8: test_horus_binary ..............................   Passed    0.16 sec
 9/15 Test  #9: test_ldpc_enc_dec ..............................   Passed    0.16 sec
10/15 Test #10: test_ldpc_enc_dec_HRAb_396_504 .................   Passed    0.43 sec
11/15 Test #11: test_ldpc_check ................................   Passed    0.26 sec
12/15 Test #12: test_FSK_modem_mod_demod .......................   Passed    0.07 sec
13/15 Test #13: test_FreeDV_API_700D_backwards_compatability ...   Passed    0.02 sec
14/15 Test #14: test_FreeDV_API_700D_AWGN_BER ..................   Passed    0.34 sec
15/15 Test #15: test_FreeDV_API_700D_AWGN_BER_Interleave .......   Passed    0.35 sec
93% tests passed, 1 tests failed out of 15
The following tests FAILED:
          2 - test_COHPSK_modem_octave_port (Failed)
 1/16 Test  #1: tst_ldpc_enc .....................   Passed   20.77 sec
 2/16 Test  #2: tst_ldpc_dec_ideal ...............   Passed   22.67 sec
 3/16 Test  #3: tst_ldpc_dec_noise ...............   Passed   27.92 sec
 4/16 Test  #4: tst_ofdm_mod_plain ...............   Passed   27.02 sec
 5/16 Test  #5: tst_ofdm_mod_ldpc ................   Passed   21.59 sec
 6/16 Test  #6: tst_ofdm_demod_quick .............   Passed   30.32 sec
 7/16 Test  #7: tst_ofdm_demod_ideal .............   Passed   24.18 sec
 8/16 Test  #8: tst_ofdm_demod_AWGN ..............   Passed   24.53 sec
 9/16 Test  #9: tst_ofdm_demod_fade ..............   Passed   62.91 sec
10/16 Test #10: tst_ofdm_demod_ldpc ..............   Passed   18.00 sec
11/16 Test #11: tst_ofdm_demod_ldpc_AWGN .........   Passed   60.49 sec
12/16 Test #12: tst_ofdm_demod_ldpc_fade .........   Passed  149.17 sec
13/16 Test #13: tst_codec2_enc_1300 ..............   Passed   35.13 sec
14/16 Test #14: tst_codec2_enc_700C ..............   Passed   25.30 sec
15/16 Test #15: tst_codec2_dec_1300 ..............   Passed   33.36 sec
16/16 Test #16: tst_codec2_dec_700C ..............   Passed   17.92 sec
100% tests passed, 0 tests failed out of 16
```

**Comment by drowe67** [comment]
What git hash is that?  I have added error reporting to the .travis.yml file so it should be verbose when it fails  It's also passing on Travis, which is Ubuntu 16.

**Comment by db4ple** [comment]
It seems octave-signal was missing in the docker image

**Pull request merged**
