### PR TITLE
Bump codec2 to 1.0.0.

### PR DESCRIPTION
**Pull request by tmiw**
Bumps version number of Codec2 to 1.0.0 and includes "make dist" changes from https://github.com/drowe67/freedv-gui/pull/152.

### CODE REVIEW

**Comment by tmiw** [comment]
@drowe67, were there any other PRs that should get in prior to merging this one? Also, what should LPCNet be bumped to if anything?

**Comment by drowe67** [comment]
Thanks @tmiw, nothing else I'd like to merge at this stage,  Hmm, not sure about LPCNet, good question :thinking: 

@hobbes1069 - I think we have Codec 2 repo ready for the 1.0 release.  It's been tested for a while and no further bugs have shown up.

**Comment by tmiw** [comment]
Hmm, should the stm32 fixes get in too, or is 1.0 intended to be a release just for regular PCs?

**Comment by drowe67** [comment]
I'm inclined to leave them until afterwards.  We can also make a new firmware release and update the stm32  `README.md`

**Comment by drowe67** [comment]
@tmiw so I think we are good for a v1.0 release.  Do you agree? We've had quite a bit of testing via your recent freedv-gui test releases, and it's been some time since we've found a bug in libcodec2. 

If you are happy I'll merge this PR, and add a tag :slightly_smiling_face: ?

**Comment by tmiw** [comment]
@drowe67, sounds good. 👍

**Pull request merged**
