### PR TITLE
Remove DFU targets and update documentation

### PR DESCRIPTION
**Pull request by tmiw**
Updates the STM32 build to reflect the recommended use of STM32CubeProgrammer for Windows users over DfuSeUtil. Original comment on this [here](https://github.com/drowe67/codec2/pull/254#issuecomment-966551282).

### CODE REVIEW

**Comment by tmiw** [comment]
@drowe67, I haven't heard much on this. Anything else needed?

**Comment by drowe67** [comment]
@tmiw thanks for the reminder :slightly_smiling_face:  I will take a look later this week (currently on a short vacation).

**Comment by drowe67** [comment]
@tmiw - do we need to see if some SM1000 users can work with this before merging?  Walter perhaps?

I'm currently running all the sm1000 tests on `bear`.

**Comment by drowe67** [comment]
Builds Ok and stm32 ctests all pass :+1:

**Comment by tmiw** [comment]
> @tmiw - do we need to see if some SM1000 users can work with this before merging? Walter perhaps?
> 
> I'm currently running all the stm32 tests on `bear`.

I took a look at the changes again and realized that the firmware version table was broken. Just checked in a fix.

Also, I posted https://groups.google.com/g/digitalvoice/c/1RpW8JVRho0/m/Z1TWMDONBQAJ asking for assistance/feedback.

**Comment by tmiw** [comment]
@drowe67, I've updated the Windows instructions per feedback from Walter. 👍

**Pull request merged**
