### PR TITLE
Make `rx_filter_coh()` static

### PR DESCRIPTION
**Pull request by xtkoba**
Downstream issue: https://bugs.gentoo.org/817437

### CODE REVIEW

**Comment by drowe67** [comment]
I also noticed he ctests haven't run automatically.  I wonder if that's because it's an external repo :thinking:

**Comment by tmiw** [comment]
FWIW, "inline" actually did improve performance a bit for 700C on my system. It seems weird that it would be causing problems on some systems, though, so it's probably better to undo that for the time being.

**Comment by drowe67** [comment]
> FWIW, "inline" actually did improve performance a bit for 700C on my system. It seems weird that it would be causing problems on some systems, though, so it's probably better to undo that for the time being.

Well if it's useful for us, and @xtkoba can't explain this PR as I requested above, I'm not inclined to merge it.  Perhaps if we understand the reasoning we can work out a way to satisfy every ones needs.  If there is no response to my question in another week, I'll close this PR.  We can always re open it later.

**Comment by drowe67** [comment]
Closed as no response from OP to our questions.

**Pull request closed without merging**
