### PR TITLE
Begin data mode conversion

### PR DESCRIPTION
**Pull request by srsampson**
Continue development of OFDM modem C code to support HF data modes, which have been prototyped in Octave.

This work started in https://github.com/drowe67/codec2/pull/126 and https://github.com/drowe67/codec2/pull/138.

## Demos

1. Uncoded C Tx, Octave Rx:
   ```
   $ cd codec2/build_liunx
   $ ./src/ofdm_mod --mode datac1 --in /dev/zero --testframes 5 --verbose 1 > test.raw
   octave:66> ofdm_rx("../build_linux/test.raw","datac1")
   ```

1. Uncoded C Tx & Rx:
   ```
   $ ./src/ofdm_mod --mode datac1 --in /dev/zero --testframes 20 | ./src/ofdm_demod --mode datac1 --out /dev/null --testframes --verbose 2
   ```

1. Coded C Tx & Rx:
   ```
   $ ./src/ofdm_mod --mode datac1 --ldpc --in /dev/zero --testframes 20 | ./src/ofdm_demod --mode datac1 --ldpc --out /dev/null --testframes --verbose 2
   ```

## TODO

1. ~~C Tx to Octave Rx on first data mode.~~
1. Shoud we change  `ofdm_mod(struct OFDM *ofdm, COMP *result, const int *tx_bits)` to `ofdm_mod(struct OFDM *ofdm, COMP *result, const uint8_t *tx_bits)`?  I'm seeing a few char->int conversions about.
1. ~~Reconcile variable names between Octave and e.g. Nbitsperframe in ofdm_lib.m, which is equivalent to bitsperframe in ofdm.c, but different to Nbitsperframe in ofdm_mod.c~~
1. run stm32 tests (have had one pass at this, but do a final check)
1. ~~Clean up uncoded error counting in coded/uncoded case - uncoded case could perhaps use `count_uncoded_errors()`~~
1. Consider removing `rx_bits[]` output from `ofdm_demod()` and friends as I think we only ever use the `ofdm->rx_np[]` output.

### CODE REVIEW

**Comment by drowe67** [comment]
Nice start @srsampson :+1: 

We actually want to keep the original state machine unmodified, to support 700D and 2020, and add a new state machine just for data modes.  All I did in https://github.com/drowe67/codec2/pull/141/commits/48f24e6338531fa626c47514bba8a8721145f56f was rename your latest state machine function :smile: 

Looks like we are close to getting an uncoded C Tx working with a data mode - I'll have a go at that over the weekend, and see if it can interoperate with the Octave Rx.

**Comment by srsampson** [comment]
I might have just reverted some of your code. Let me check and fix that.

**Comment by drowe67** [comment]
@srsampson OK thanks for letting me know - I'll work on some other stuff while you sort that out.  I might put the C version of [ofdm_init_mode](https://github.com/drowe67/codec2/blob/master/octave/ofdm_lib.m#L220) in a new .c file as it combines OFDM and LDPC stuff.

**Comment by drowe67** [comment]
OK scratch that I might put `ofdm_init_mode` in `ofdm.c` after all, no LDPC mentioned in that function.

**Comment by drowe67** [comment]
@srsampson I fixed the test fails as part of https://github.com/drowe67/codec2/pull/141/commits/8d1faa431a25d4f17bb6267dcedc8b68c82a16d4 - hope that didn't clash with anything you were doing :slightly_smiling_face:

**Comment by srsampson** [comment]
> @srsampson I fixed the test fails as part of [8d1faa4](https://github.com/drowe67/codec2/commit/8d1faa431a25d4f17bb6267dcedc8b68c82a16d4) - hope that didn't clash with anything you were doing

No sir! Clash away! I haven't been on the computer much this afternoon. Excellent fix!

**Comment by srsampson** [comment]
Wow! You are cranking out the code! I'll be on the road this weekend. Have to haul some old car parts to Texas.

**Comment by drowe67** [comment]
> Wow! You are cranking out the code! I'll be on the road this weekend. Have to haul some old car parts to Texas.

Thanks Steve, yes I'm moving along nicely, aiming for the uncoded Rx.  Have a nice trip - we aren't really allowed to travel interstate here, but plenty to do inside my (currently covid-free) state so I'm happy with that.

**Comment by drowe67** [comment]
@srsampson well that blew up quickly :grin: 

The number of files changed is rather large, so I think I better merge soon. I'm pleased that quite a bit of code was removed, it shows our design is maturing well.

When convenient, could you pls review?

Some ideas for future PRs:
1. A way to have mode-defined unique words, required for the low SNR `datac3` mode.
1. Merging https://github.com/drowe67/codec2/pull/130 and start coding up QAM support (uncoded first) in C.
1. `ofdm_put_test_bits` that works for coded and uncoded modes, to test bit stream output from `ofdm_demod`.
1. A FreeDV API mode for data, we probably just need one `freedvapi_data.c` file for all modes.

**Comment by srsampson** [comment]
Wow! Looks really good David. Quite a cleanup and all tests passing. Yes, pretty big branch, let's merge and close this one.

**Comment by srsampson** [comment]
Maybe instead of a new FreeDV mode, a new FreeDD application?

**Comment by drowe67** [comment]
I built freedv-gui against this branch and decoded the 2020 and 700D examples OK :+1:

**Pull request merged**
