### PR TITLE
Interleaving doesn't seem to function correctly

### PR DESCRIPTION
**Pull request by srsampson**
There was an error in the choose_interleaver_b() function where it was only using half the table, by dividing the table size by 2 * int size.

Running the ofdm_mod and ofdm_demod examples in the README_ofdm often results in truncated or garbled audio. For example:

./c2enc 700C ../../raw/ve9qrp.raw - --bitperchar | ./ofdm_mod --ldpc 1 --interleave 16 | ./cohpsk_ch - - -24 --Fs 8000 -f -10 --fast | ./ofdm_demod --ldpc 1 --verbose 1 --interleave 16 | ./c2dec 700C - - --bitperchar | aplay -f S16

Is mostly garbled. In theory it should be no worse. The idea being, to defeat the ionosphere.

### CODE REVIEW

**Comment by srsampson** [comment]
Removing cohpsk_ch from piped options seems to work with interleave 16. --slow, --fast, and --faster have varying levels of garble.

I'm not sure if that response is normal for the simulation.

**Comment by srsampson** [comment]
```
./c2enc 700C ../../raw/hts.raw - --bitperchar | ./ofdm_mod --ldpc 1 --interleave 16 | ./ofdm_demod --ldpc 1 --interleave 16 | ./c2dec 700C - - --bitperchar | play --type s16 --rate 8000 --channels 1 -
```
Seems to truncate the audio more as the interleave increases.

**Comment by srsampson** [comment]
I added 2020 interleaver primes for options 1,2,4,8,16 in gp_interleaver.c
As far as I could determine it uses 252 symbols (504 bits) in interleave 1.

I don't think this changes anything for 2020 mode, as the error was in table indexes further than halfway (about 10 indexes in) and 2020 interleave 1 at 252 was below that.

**Comment by drowe67** [comment]
> I added 2020 interleaver primes for options 1,2,4,8,16 in gp_interleaver.c
> As far as I could determine it uses 252 symbols (504 bits) in interleave 1.

Yep, as per https://github.com/drowe67/codec2/blob/master/octave/modem_codec_frame_design.ods

However I don't think the 2020 freedv_api.c code supports interleavers other than 1.  I didn't bother as no one was using long interleavers with 700D, and it's complex C code to write.

**Comment by drowe67** [comment]
@srsampson so I just tried this branch, and ran the example at the top of this PR, but it sounds garbled.  Am I doing something wrong?  

Can you explain how I can run an A/B test to demonstrate the effects of his problem and the fix?

**Comment by drowe67** [comment]
OK so on ```master``` I just tried:
```
./c2enc 700C ../../raw/ve9qrp.raw - --bitperchar | ./ofdm_mod --ldpc 1 --interleave 16 | ./ofdm_demod --ldpc 1 --verbose 1 --interleave 16 | ./c2dec 700C - - --bitperchar | aplay -f S16
interleave_frames: 16
Phase Estimate Switching: Auto
Nbits: 1792, b not found!
ofdm_mod: /home/david/codec2/src/gp_interleaver.c:82: choose_interleaver_b: Assertion `0' failed.
```
Is that the smoking gun?

**Comment by srsampson** [comment]
De plane! de plane!

yes, due to the table indexing function.

**Comment by srsampson** [comment]
> I added 2020 interleaver primes for options 1,2,4,8,16 in gp_interleaver.c
> As far as I could determine it uses 252 symbols (504 bits) in interleave 1.
> 
> I don't think this changes anything for 2020 mode, as the error was in table indexes further than halfway (about 10 indexes in) and 2020 interleave 1 at 252 was below that.

I thought maybe in FreeDV the options might allow 2-16 for mode 2020, so thought just to keep it from blowing up in that function. Maybe I'm just pushing the problem forward, and if someone does type in 2 it will fail someplace else.

Maybe need to remove that option for 2020 for now??

**Comment by drowe67** [comment]
I think it's working, two runs with different interleaver depths:

```
./ofdm_mod --in /dev/zero --ldpc 1 --interleave 1 --testframes 60 | ./cohpsk_ch - - -24 --Fs 8000 -f -10 --fast | ./ofdm_demod --out /dev/null --testframes --verbose 1 --ldpc 1 --interleave 1
<snip>
BER......: 0.1135 Tbits: 77952 Terrs:  8846
Coded BER: 0.0513 Tbits: 38976 Terrs:  2001
```

```
./ofdm_mod --in /dev/zero --ldpc 1 --interleave 16 --testframes 60 | ./cohpsk_ch - - -24 --Fs 8000 -f -10 --fast | ./ofdm_demod --out /dev/null --testframes --verbose 1 --ldpc 1 --interleave 16
<snip>
BER......: 0.0991 Tbits: 75264 Terrs:  7460
Coded BER: 0.0107 Tbits: 37632 Terrs:   403
```
Note the depth 16 test has less bits at the output, as you loose a lot of frames while it syncs up.

**Comment by drowe67** [comment]
A few sanity checks:

Make sure we can decode an existing 2020 and 700D (depth 1) modulated files:
```
./freedv_rx 2020 ~/Desktop/all_2020.wav - | aplay -fS16_LE -r 16000
./freedv_rx 2020 ~/Desktop/ve9qrp_700d - | aplay -fS16_LE
```
:+1:

**Comment by drowe67** [comment]
This is interesting, with no noise but a fading channel, we still get the fading introducing bit errors as occasionally the constellation points end up near the origin, but 0 coded BER with a large interleaver, so Yayy for interleaving!

```
./ofdm_mod --in /dev/zero --ldpc 1 --interleave 16 --testframes 60 | ./cohpsk_ch - - -100 --Fs 8000 -f -10 --fast | ./ofdm_demod --out /dev/null --testframes --verbose 1 --ldpc 1 --interleave 16
<snip>
BER......: 0.0206 Tbits: 82432 Terrs:  1698
Coded BER: 0.0000 Tbits: 41216 Terrs:     0
```

And here's a long simulation with a perfect channel that proves the interleaver doesn't introduce any bit errors:
```
./ofdm_mod --in /dev/zero --ldpc 1 --interleave 16 --testframes 60 | ./ofdm_demod --out /dev/null --testframes --verbose 1 --ldpc 1 --interleave 16
BER......: 0.0000 Tbits: 1487360 Terrs:     0
Coded BER: 0.0000 Tbits: 743680 Terrs:     0
```
If the interleaver had issues it might introduce errors that the FEC then corrected.

**Comment by drowe67** [comment]
> Maybe need to remove that option for 2020 for now??

Yes pelase - I think it's unlikely we'll add interleaving to 2020, it's really for higher SNRs.

**Comment by drowe67** [comment]
BTW we have a ctest that tests at depth 8, so the bug must have kicked in after that.

**Comment by drowe67** [comment]
One reaming issue, this:

```
./c2enc 700C ../../raw/ve9qrp.raw - --bitperchar | ./ofdm_mod --ldpc 1 --interleave 16 | ./cohpsk_ch - - -24 --Fs 8000 -f -10 --fast | ./ofdm_demod --ldpc 1 --verbose 1 --interleave 16 | ./c2dec 700C - - --bitperchar | aplay -f S16
```

... still sounds worse that depth 1 or 8.  Depth 16 is completely garbled, 8 is quite good. Any ideas why?  Wonder if we are overrunning a buffer somewhere.

**Comment by srsampson** [comment]
> One reaming issue, this:
> 
> ```
> ./c2enc 700C ../../raw/ve9qrp.raw - --bitperchar | ./ofdm_mod --ldpc 1 --interleave 16 | ./cohpsk_ch - - -24 --Fs 8000 -f -10 --fast | ./ofdm_demod --ldpc 1 --verbose 1 --interleave 16 | ./c2dec 700C - - --bitperchar | aplay -f S16
> ```
> 
> ... still sounds worse that depth 1 or 8. Depth 16 is completely garbled, 8 is quite good. Any ideas why? Wonder if we are overrunning a buffer somewhere.

That is the area of the code I am looking at. So far, the buffer creation in the API seems pretty reasonable to me.

**Comment by srsampson** [comment]
> > Maybe need to remove that option for 2020 for now??
> 
> Yes pelase - I think it's unlikely we'll add interleaving to 2020, it's really for higher SNRs.

Probably best done in FreeDV as a disable after mode selection. I wonder if at the same time, there should be a check to make sure the odd values are not accepted, just the even ones.

**Comment by drowe67** [comment]
> That is the area of the code I am looking at. So far, the buffer creation in the API seems pretty reasonable to me.

You know I think I hit this one before, but may have decided to leave it as depth 16 was pretty uncommon.  So don't knock yourself out on it .....

**Comment by srsampson** [comment]
> > That is the area of the code I am looking at. So far, the buffer creation in the API seems pretty reasonable to me.
> 
> You know I think I hit this one before, but may have decided to leave it as depth 16 was pretty uncommon. So don't knock yourself out on it .....

Is the Unique Sync word only in the first interleave frame? I was thinking maybe it's garbled because it falls out of sync. (Note to myself to check)

Yes, 16 seems a bit wishful thinking maybe.

**Comment by drowe67** [comment]
@srsampson I there is the regular UW on every frame, the interleaver then gets sync on top of that, IIRC by looking for the offset where the LDPC code converges.

I think you've fixed the actual issue - thanks :+1: . Debugging the audio at depth 16 is optional, and the 2020 interleaver lockout is a separate issue.  So I'm happy to merge whenever you are ready.

**Comment by srsampson** [comment]
> @srsampson there is the regular UW on every frame, the interleaver then gets sync on top of that, IIRC by looking for the offset where the LDPC code converges.
> 
> I think you've fixed the actual issue - thanks  . Debugging the audio at depth 16 is optional, and the 2020 interleaver lockout is a separate issue. So I'm happy to merge whenever you are ready.

Yes, you can merge and close this, as I am off on a tangent..

**Pull request merged**
