### PR TITLE
stm32 maintenance

### PR DESCRIPTION
**Pull request by drowe67**
1. [SPARE_RAM change](https://github.com/drowe67/codec2/pull/243/files#diff-459a8b05efa8b02867b4f6a67ea2bb8b3c65a9ca1659a5b3db33e96079750ec2)
2. Retire gdb_stdio, as this has been deprecated
3. rm some unused unit tests.  I've left in a bunch of files and demos for USB support as one day it might be nice to add a USB console and CLI to the SM1000.

Checks:
1. scratch checkout and rebuild :heavy_check_mark: 
1. stm32 ctests pass :heavy_check_mark:

### CODE REVIEW

**Comment by tmiw** [comment]
Seems reasonable to me 👍

**Comment by drowe67** [comment]
@srsampson or @tmiw - could you pls try a scratch build of this PR?  I want to make sure I haven't rm-ed one to many files .... it's building and running ctests OK for me.

**Comment by tmiw** [comment]
It built fine on bear. Running the ctests now.

**Comment by srsampson** [comment]
I didn't make it past test 2:
```
2: Breakpoint 1 at 0x8010d04: file /home/ssampson/ctest/codec2/stm32/unittest/src/startup_stm32f4xx.s, line 119.
2: Function "abort" not defined.
2: Make breakpoint pending on future shared library load? (y or [n]) [answered N; input not from terminal]
2: 
2: ----------------------------STARTING PROGRAM-------------------------
2: 
2: Note: automatically using hardware breakpoints for read-only addresses.
2: LDPC encode test and profile
2: Error opening input file
```

**Comment by srsampson** [comment]
Disregard, I skipped the build_linux/make and I guess you have to do that before the stm32/make.

**Comment by srsampson** [comment]
Works fine here:
```
100% tests passed, 0 tests failed out of 28

Total Test time (real) = 1146.08 sec
```

**Comment by drowe67** [comment]
> It built fine on bear. Running the ctests now.
> 
> EDIT: two failures:
> 
> ```
> The following tests FAILED:
> 	 10 - tst_ofdm_demod_fade (Failed)
> 	 13 - tst_ofdm_demod_ldpc_fade (Failed)
> Errors while running CTest
> ```

Running OK for me, you may have missed running the x86 ctests, which generate the fading files.

Thanks for helping out @tmiw @srsampson

**Comment by srsampson** [comment]
I'm in favor of adding the *.float fading files permanently to ```raw``` directory. I keep them in my Download directory and have to copy them to ```raw``` every time I create a new repo.

**Comment by drowe67** [comment]
> I'm in favor of adding the *.float fading files permanently to `raw` directory. I keep them in my Download directory and have to copy them to `raw` every time I create a new repo.

They are rather large, about 15Mbyte total.  They get created automatically by the ctests but perhaps we could make this part of the cmake build procedure for unit tests.

**Comment by srsampson** [comment]
Yes, that would be better. For some reason my builds never create them. I have to manually create or move them from temp storage. I just figured everyone did the same.

**Comment by drowe67** [comment]
> Yes, that would be better. For some reason my builds never create them. I have to manually create or move them from temp storage. I just figured everyone did the same.

The ctests create them at present. The GitHub actions generate them every time we push (as all tests pass), so they must be generated auto-magically in that case.  So for now just run the ctests every time you do a fresh build.

They could also be created at run time in `cohpsk_ch`, using code, PathSim does it that way.  They are just filtered Gaussian numbers, I'm just using Octave to generate them as it's easy.

**Pull request merged**
