### PR TITLE
FreeDV 2020C

### PR DESCRIPTION
**Pull request by drowe67**
Following on from #274. In the [blog post](https://www.rowetel.com/?p=8014) write up of 2020A/2020B, one of the further work items was to try 2020B with a high rate FEC code that can protect all bits.  The idea is that once a threshold SNR is reached, 2020C will be error free.

@billcowley has kindly designed a suitable (212,158) LDPC code.

Note branch is named dr-2020B as 2020C was initially derived from 2020B.

TODO:
1. Build up mode in FreeDV API :heavy_check_mark: 
2. ctests :heavy_check_mark: 
3. "Ear protection" - some work on reducing loud noises due to uncorrected bit errors (see below).  Applied to all LPCNet (2020) modes  :heavy_check_mark:
4. Test OTA.  One day automated test campaign was inconclusive - didn't show any difference between 2020B and 2020C (see below). :heavy_check_mark:

Simulation on an AWGN channel at about 6dB SNR, 2020C sounds better than 2020B (which has unequal error protection):
```
./src/freedv_tx 2020C ~/LPCNet/wav/all.wav - --clip 1 | ./src/ch - - --No -21 | ./src/freedv_rx 2020C - - --vv | aplay -f S16_LE -r 16000
<snip>
ch: SNR3k(dB):     6.27  C/No....:    41.04
ch: peak.....: 17543.86  RMS.....: 10045.32   CPAPR.....:  4.84
```

### CODE REVIEW

**Comment by drowe67** [comment]
@tmiw - I'll shoot for having 2020C ready for the May FreeDV activity day.

**Comment by tmiw** [comment]
> @tmiw - I'll shoot for having 2020C ready for the May FreeDV activity day.

Can we increment LPCNet and Codec2 version numbers for this as well? I suspect the issue one person had on the digitalvoice list may be in part due to incompatible versions, so I want to rule that out by updating freedv-gui dependencies.

**Comment by drowe67** [comment]
> > @tmiw - I'll shoot for having 2020C ready for the May FreeDV activity day.
> 
> Can we increment LPCNet and Codec2 version numbers for this as well? I suspect the issue one person had on the digitalvoice list may be in part due to incompatible versions, so I want to rule that out by updating freedv-gui dependencies.

Do you mean bumping the API version number returned by `freedv_get_version(void)`? Or the version number in `CMakeLists.txt`?  I'm OK with either.

The bug report on the mailing list was not articulated very well, I'm inclined to ignore it rather than try to guess what it means.  If its real someone will make a clear bug report.

**Comment by tmiw** [comment]
> Do you mean bumping the API version number returned by `freedv_get_version(void)`? Or the version number in `CMakeLists.txt`? I'm OK with either.

`CMakeLists.txt` as that controls what version is encoded in the .deb files. 👍 

> The bug report on the mailing list was not articulated very well, I'm inclined to ignore it rather than try to guess what it means. If its real someone will make a clear bug report.

Yep. I asked for further information several times with no response either time, so /shrug

**Comment by drowe67** [comment]
# Ear Protection

During initial OTA tests I looked into the effect of uncorrected bit errors, e.g. when the FEC can't correct all errors, and we pass frames that have bit errors into the LPCNet decoder.  I used an off air sample (ground wave channel SNR of 4dB), which had lots of pops and clicks, and R2D2 noises when decoded.

We can use the LDPC decoder pcc metric to tell us when it has correctly decoded a FEC codeword. I tried muting the output with when a FEC codeword was not correctly decoded, but this resulted in about 50% of the speech being lost.  In 2020E there are three LPCNet frames (90ms) in one LDPC FEC codeword.  So we also lose quite a big chunk of speech with this approach - 90ms at a time.

Looking at the RX logs we can see many sequences that have have poor LDPC codeword decoding (high `iter`ations, low `pcc`), which explains why we lose so much speech with the muting approach.
```
197 st: synced euw:  0 0 f:  25.5 pbw: 1 snr:  4.4 eraw:   0 ecdd:   0 iter:   5 pcc:  56 rxst: -BS-
198 st: synced euw:  0 0 f:  25.5 pbw: 1 snr:  4.4 eraw:   0 ecdd:   0 iter:   3 pcc:  56 rxst: -BS-
199 st: synced euw:  1 0 f:  25.4 pbw: 1 snr:  4.7 eraw:   0 ecdd:   0 iter:   5 pcc:  56 rxst: -BS-
200 st: synced euw:  1 0 f:  25.5 pbw: 1 snr:  4.6 eraw:   0 ecdd:   0 iter:   5 pcc:  56 rxst: -BS-
201 st: synced euw:  0 0 f:  25.4 pbw: 1 snr:  4.4 eraw:   0 ecdd:   0 iter: 100 pcc:  55 rxst: EBS-
202 st: synced euw:  0 0 f:  25.3 pbw: 1 snr:  4.4 eraw:   0 ecdd:   0 iter:   8 pcc:  56 rxst: -BS-
203 st: synced euw:  1 0 f:  25.4 pbw: 1 snr:  4.4 eraw:   0 ecdd:   0 iter:  91 pcc:  56 rxst: -BS-
204 st: synced euw:  3 0 f:  25.3 pbw: 1 snr:  4.5 eraw:   0 ecdd:   0 iter:   6 pcc:  56 rxst: -BS-
205 st: synced euw:  1 0 f:  25.2 pbw: 1 snr:  5.0 eraw:   0 ecdd:   0 iter:   9 pcc:  56 rxst: -BS-
206 st: synced euw:  0 0 f:  25.3 pbw: 1 snr:  5.0 eraw:   0 ecdd:   0 iter: 100 pcc:  32 rxst: EBS-
207 st: synced euw:  0 0 f:  25.3 pbw: 1 snr:  5.0 eraw:   0 ecdd:   0 iter:   2 pcc:  56 rxst: -BS-
208 st: synced euw:  2 0 f:  25.3 pbw: 1 snr:  4.9 eraw:   0 ecdd:   0 iter: 100 pcc:  41 rxst: EBS-
209 st: synced euw:  2 0 f:  25.2 pbw: 1 snr:  4.8 eraw:   0 ecdd:   0 iter: 100 pcc:  55 rxst: EBS-
210 st: synced euw:  1 0 f:  25.1 pbw: 1 snr:  4.7 eraw:   0 ecdd:   0 iter:   4 pcc:  56 rxst: -BS-
211 st: synced euw:  0 0 f:  25.2 pbw: 1 snr:  4.6 eraw:   0 ecdd:   0 iter:   5 pcc:  56 rxst: -BS-
```

Clearly - there is still some useful speech, even in frames with errors. So my next approach was [some code](https://github.com/drowe67/codec2/pull/319/commits/c3d5b77fbe7870a5200f933841a49d7a5ce6c1c7) to limit the amplitude of any obvious high amplitude clicks, this will hopefully make low SNR decoded speech easier to listen to.  Top is the original, below the "ear protection" ouput, which has some of the higher level spikes removed.

Screenshot from 2022-08-12 07-33-24

**Comment by drowe67** [comment]
# OTA Test Campaign

1. Aug 12 2022, David's house and `sdr.ironstonerange.com`, about 100km away.  The groundwave/NVIS combination often leads to fast fading, 58 samples collected over the day, 700E/2020/2020B/2020C sent 2 minutes apart at around 50W peak.
2. Many samples around 5dB SNR for 2020, 10dB for 2020B/C, suggesting the Doppler or delay spread on this channel favored B/C over 2020.
3. However the all sounded pretty good, no evidence of C>B.  At 10dB SNR there aren't many bit errors.
4. I think all 2020 modes sounded better than SSB.  SSB was a fine copy, but it's just band limited compared to the 2020 modes.  It would be interesting to see if this matches real world freedv-gui use.

**Comment by drowe67** [comment]
@tmiw :point_up: Outcomes of 2020C work.  I'll merge this soon.  No clear indication of 2020C > 2020B :thinking:

**Pull request merged**
