### PR TITLE
Update codec2 for removal of LPCNet circular build dependancy

### PR DESCRIPTION
**Pull request by drowe67**
`codec2` tweaks for https://github.com/drowe67/LPCNet/pull/43:

1. Update READMEs for new build procedure
2. Update GitHub actions
3. Bump version to 1.0.7
4. Tweak a few ctests to run reliably on OSX

### CODE REVIEW

**Comment by drowe67** [comment]
@tmiw in https://github.com/drowe67/LPCNet/pull/43#issue-1342677127 you mentioned some ctests failing - was that just on the OSX platform?  A couple of them look like tests I have added recently (FDMDV and 2020C), they might need BER threshold tweaking, or longer runs.

**Comment by tmiw** [comment]
> @tmiw in [drowe67/LPCNet#43 (comment)](https://github.com/drowe67/LPCNet/pull/43#issue-1342677127) you mentioned some ctests failing - was that just on the OSX platform? A couple of them look like tests I have added recently (FDMDV and 2020C), they might need BER threshold tweaking, or longer runs.

The FDMDV one I was able to fix fairly easily. I'll push shortly. However, the others are still having issues for various reasons:

```
test 18
    Start 18: test_COHPSK_modem_freq_offset

18: Test command: /bin/sh "-c" "set -x; /Users/mooneer/devel/codec2/build_osx/src/cohpsk_get_test_bits - 5600 | /Users/mooneer/devel/codec2/build_osx/src/cohpsk_mod - - | /Users/mooneer/devel/codec2/build_osx/src/ch - - --No -40 -f -30 --Fs 7500 | /Users/mooneer/devel/codec2/build_osx/src/cohpsk_demod -v - - 2>log.txt | /Users/mooneer/devel/codec2/build_osx/src/cohpsk_put_test_bits - ; ! grep 'lost sync' log.txt"
18: Test timeout computed to be: 1500
18: + /Users/mooneer/devel/codec2/build_osx/src/cohpsk_get_test_bits - 5600
18: + /Users/mooneer/devel/codec2/build_osx/src/cohpsk_mod - -
18: + /Users/mooneer/devel/codec2/build_osx/src/ch - - --No -40 -f -30 --Fs 7500
18: + /Users/mooneer/devel/codec2/build_osx/src/cohpsk_demod -v - -
18: + /Users/mooneer/devel/codec2/build_osx/src/cohpsk_put_test_bits -
18: ch: Fs: 7500 NodB: -40.00 foff: -30.00 Hz fading: 0 nhfdelay: 0 clip: 32767.00 ssbfilt: 1 complexout: 0
18: diversity: 1
18: ch: SNR3k(dB):    16.22  C/No....:    50.99
18: ch: peak.....:  7111.14  RMS.....:  3541.86   CPAPR.....:  6.05 
18: ch: Nsamples.:    60000  clipped.:     0.00%  OutClipped:  0.00%
18: BER: 0.000 Nbits: 4312 Nerrors: 0
18: + grep 'lost sync' log.txt
18:   [19] lost sync ....
1/1 Test #18: test_COHPSK_modem_freq_offset ....***Failed    1.56 sec

test 21
    Start 21: test_OFDM_modem_octave_port_Nc_31

21: Test command: /bin/sh "-c" "NC=31 PATH_TO_TOFDM=/Users/mooneer/devel/codec2/build_osx/unittest/tofdm DISPLAY="" octave-cli --no-gui -qf /Users/mooneer/devel/codec2/octave/tofdm.m"
21: Environment variables: 
21:  CML_PATH=/Users/mooneer/devel/codec2/build_osx/cml
21: Test timeout computed to be: 1500
21: cml_support = 1
21: Nc = 31 LDPC testing: 0
21: Nbitsperframe: 434
21: 
21: Running C version....
21: path_to_tofdm = ../build_linux/unittest/tofdm
21: path_to_tofdm = /Users/mooneer/devel/codec2/build_osx/unittest/tofdm
21: setting path from env var
21: Nc = 31
21: LDPC disabled
21: Assertion failed: (isnan(EsNodB) == 0), function ofdm_esno_est_calc, file ofdm.c, line 1821.
21: Nc = 31 ofdm_bitsperframe: 434
21: warning: using the gnuplot graphics toolkit is discouraged
21: 
21: The gnuplot graphics toolkit is not actively maintained and has a number
21: of limitations that are unlikely to be fixed.  Communication with gnuplot
21: uses a one-directional pipe and limited information is passed back to the
21: Octave interpreter so most changes made interactively in the plot window
21: will not be reflected in the graphics properties managed by Octave.  For
21: example, if the plot window is closed with a mouse click, Octave will not
21: be notified and will not update its internal list of open figure windows.
21: The qt toolkit is recommended instead.
21: pilot_samples............: OK
21: tx_bits..................: OK
21: tx.......................: OK
21: rx.......................: FAIL (2361414365005732642816.000000)
21: rxbuf in.................: FAIL (2361414365005732642816.000000)
21: rxbuf....................: FAIL (1399356660744137998336.000000)
21: rx_sym...................: FAIL (9067831371911147949129728.000000)
21: phase_est_pilot..........: FAIL (2.978755)
21: rx_amp...................: FAIL (1511305194347327580536832.000000)
21: timing_est...............: FAIL (1.500000)
21: timing_valid.............: FAIL (0.100000)
21: timing_mx................: FAIL (0.052657)
21: coarse_foff_est_hz.......: OK
21: sample_point.............: FAIL (0.800000)
21: foff_est_hz..............: FAIL (0.015813)
21: rx_bits..................: FAIL (0.052304)
21: mean_amp_log.............: FAIL (151130499258606422065152.000000)
21: snr_log..................: FAIL (1.335379)
21: 
21: passes: 4 fails: 14
1/1 Test #21: test_OFDM_modem_octave_port_Nc_31 ...***Failed  Required regular expression not found. Regex=[fails: 0
] 77.08 sec

test 74
    Start 74: test_freedv_api_2020C_mpd

74: Test command: /bin/sh "-c" "cd /Users/mooneer/devel/codec2/build_osx/src;
                            dd bs=32000 count=60 if=/dev/zero |
                            ./freedv_tx 2020C - - --testframes --clip 1 |
                            ./ch - - --No -31 --mpd --fading_dir ../unittest |
                            ./freedv_rx 2020C - /dev/null --testframes"
74: Test timeout computed to be: 1500
74: ch: Fs: 8000 NodB: -31.00 foff: 0.00 Hz fading: 3 nhfdelay: 32 clip: 32767.00 ssbfilt: 1 complexout: 0
74: 60+0 records in
74: 60+0 records out
74: 1920000 bytes transferred in 3.205118 secs (599042 bytes/sec)
74: ch: SNR3k(dB):    16.50  C/No....:    51.27
74: ch: peak.....: 16485.79  RMS.....: 10314.20   CPAPR.....:  4.07 
74: ch: Nsamples.:   479520  clipped.:     0.00%  OutClipped:  0.01%
74: frames decoded: 668  output speech samples: 5760
74: BER......: 0.0204  Tbits:   164672  Terrs:     3367
74: Coded BER: 0.0103  Tbits:   103584  Terrs:     1071
74: Coded PER: 0.1702  Tpkts:      664  Tpers:      113
1/1 Test #74: test_freedv_api_2020C_mpd ........***Failed    3.34 sec
```
```

**Comment by drowe67** [comment]
@tmiw re `test_COHPSK_modem_freq_offset` can you pls post `log.txt`?  The output on my machine is:
```
8: ch: SNR3k(dB):    16.21  C/No....:    50.99
18: ch: peak.....:  7111.14  RMS.....:  3541.86   CPAPR.....:  6.05 
18: ch: Nsamples.:    60000  clipped.:     0.00%  OutClipped:  0.00%
18: BER: 0.000 Nbits: 5432 Nerrors: 0
18: + grep lost sync log.txt
1/1 Test #18: test_COHPSK_modem_freq_offset ....   Passed    0.08 sec
```
So I'm not getting a "lost sync" event, and have a few more bits demodulated.  I think whats happening on your machine is it gets a false sync on the first try, then gets a valid sync on thenext try.  That's arguably not a fail, as it's just taking a little longer on your machine. So we might just need to adjust the pass conditions.

**Comment by tmiw** [comment]
> @tmiw re `test_COHPSK_modem_freq_offset` can you pls post `log.txt`? The output on my machine is:
> 
> ```
> 8: ch: SNR3k(dB):    16.21  C/No....:    50.99
> 18: ch: peak.....:  7111.14  RMS.....:  3541.86   CPAPR.....:  6.05 
> 18: ch: Nsamples.:    60000  clipped.:     0.00%  OutClipped:  0.00%
> 18: BER: 0.000 Nbits: 5432 Nerrors: 0
> 18: + grep lost sync log.txt
> 1/1 Test #18: test_COHPSK_modem_freq_offset ....   Passed    0.08 sec
> ```
> 
> So I'm not getting a "lost sync" event, and have a few more bits demodulated. I think whats happening on your machine is it gets a false sync on the first try, then gets a valid sync on thenext try. That's arguably not a fail, as it's just taking a little longer on your machine. So we might just need to adjust the pass conditions.

Here you go: [log.txt](https://github.com/drowe67/codec2/files/9390338/log.txt)

**Comment by drowe67** [comment]
@tmiw - I've tweaked the COHPSK and 2020C tests to make them more robust to statistical variations on different arches.

Yes, `test_OFDM_modem_octave_port_Nc_31` is going to be more complex to debug.  Based on the checklist it looks like something is going wrong between the `tx` and `rx`, perhaps in the channel simulation code around line 88.  It might be interesting to bypass the channel simulation and just set `rx_log=tx_log;`. But if your not up for debugging that, it's fine to leave it for now.

**Comment by tmiw** [comment]
> @tmiw - I've tweaked the COHPSK and 2020C tests to make them more robust to statistical variations on different arches.
> 
> Yes, `test_OFDM_modem_octave_port_Nc_31` is going to be more complex to debug. Based on the checklist it looks like something is going wrong between the `tx` and `rx`, perhaps in the channel simulation code around line 88 of `tofdm.m`. It might be interesting to bypass the channel simulation and just set `rx_log=tx_log;`. But if your not up for debugging that, it's fine to leave it for now.

I added `rx_log = tx_log` to tofdm.m and ended up with the following results:

```
20: pilot_samples............: OK
20: tx_bits..................: OK
20: tx.......................: OK
20: rx.......................: FAIL (7938482348656.740234)
20: rxbuf in.................: FAIL (7938482348656.738281)
20: rxbuf....................: FAIL (4704285836241.041016)
20: rx_sym...................: FAIL (22.455041)
20: phase_est_pilot..........: FAIL (23.372557)
20: rx_amp...................: FAIL (0.116486)
20: timing_est...............: FAIL (0.700000)
20: timing_valid.............: FAIL (0.100000)
20: timing_mx................: FAIL (0.054830)
20: coarse_foff_est_hz.......: OK
20: sample_point.............: OK
20: foff_est_hz..............: FAIL (0.303557)
20: rx_bits..................: OK
20: symbol_likelihood_log....: FAIL (3.031063)
20: bit_likelihood_log.......: FAIL (3.125554)
20: detected_data............: OK
20: mean_amp_log.............: FAIL (0.054761)
20: snr_log..................: FAIL (265.351557)
20: 
20: passes: 7 fails: 14
1/2 Test #20: test_OFDM_modem_octave_port .........***Failed  Required regular expression not found. Regex=[fails: 0
] 76.23 sec
...
1: pilot_samples............: OK
21: tx_bits..................: OK
21: tx.......................: OK
21: rx.......................: FAIL (0.040750)
21: rxbuf in.................: FAIL (0.039132)
21: rxbuf....................: FAIL (0.039686)
21: rx_sym...................: FAIL (39.807813)
21: phase_est_pilot..........: FAIL (42.252557)
21: rx_amp...................: FAIL (0.121814)
21: timing_est...............: FAIL (0.700000)
21: timing_valid.............: OK
21: timing_mx................: FAIL (0.008992)
21: coarse_foff_est_hz.......: OK
21: sample_point.............: OK
21: foff_est_hz..............: FAIL (0.300246)
21: rx_bits..................: OK
21: mean_amp_log.............: FAIL (0.057229)
21: snr_log..................: FAIL (263.378989)
21: 
21: passes: 7 fails: 11
2/2 Test #21: test_OFDM_modem_octave_port_Nc_31 ...***Failed  Required regular expression not found. Regex=[fails: 0
] 81.47 sec
```

**Comment by drowe67** [comment]
Oh well, it's going to be tricky for me to fully debug without access to the actual machine.  Thanks for trying :+1: 

OK to merge this PR? I don't think it will affect anything in freedv-gui.  Once everything is stable we can tag  this repo and LPCNet.  I've already bumped the version number.

**Comment by tmiw** [comment]
> OK to merge this PR? I don't think it will affect anything in freedv-gui. Once everything is stable we can tag this repo and LPCNet. I've already bumped the version number.

Yep, we can go ahead and merge.

**Pull request merged**
