### PR TITLE
Remove tx filter deallocate from ofdm_destroy

### PR DESCRIPTION
**Pull request by srsampson**
Fix for https://github.com/drowe67/codec2/issues/102, to support multiple parallel instances.

### CODE REVIEW

**Comment by srsampson** [comment]
I knew that was going to fail, but I'm trying to think of a work-around.

**Comment by drowe67** [comment]
@srsampson I think the filter states are fine inside ```struct OFDM```, they don't get allocated when used on the SM1000.

The malloc/free code for the filter is tricky, but working correctly I think.  It could perhaps use some refactoring.

I think the issue @dave-g8kbb suggested is these:

```
static complex float *tx_uw_syms;
static int *uw_ind;
static int *uw_ind_sym;
```

get malloced/freed.  So on applications that create two instances of the OFDM modem, they dissapear when one instance is closed.

So maybe we need to move them inside ```struct OFDM``.

**Comment by srsampson** [comment]
@drowe67 I wonder if all the statics can be moved into the structure?

That way the ofdm pointer returned from one create has no affect on other creates.

**Comment by drowe67** [comment]
> @drowe67 I wonder if all the statics can be moved into the structure?
> 
> That way the ofdm pointer returned from one create has no affect on other creates.

@srsampson yes that would be ideal, I recall we were heading in that direction in stages.  IIRC the some of the static variable are used as "constants" that replaced #defines in earlier versions.

Suggest as a first step, just move any dynamically allocated variables into the struct.  If two instances of the same modem parameters are creates, that should allow multi-instance operation.

**Comment by drowe67** [comment]
@srsampson another reason for the filter states being inside the struct is to support multiple instances, as each filter will have different data flowing through it.  So with regards to the filter,  I think what we have in ```master``` is fine.

**Pull request closed without merging**
