### PR TITLE
Create a modem version with one carrier

### PR DESCRIPTION
**Pull request by srsampson**
The modem will be called with nc=1 thus ofdm_ncp will equal 0 so we need to correct for that where necessary.

### CODE REVIEW

**Comment by srsampson** [comment]
I'm playing with the tx side here. The rx side will have problems. The unique word algorithm probably needs to be replaced. I'm using ofdm_mod to interface and looking at spectrum with audacity. So far it's pretty ugly.

**Comment by srsampson** [comment]
> The modem will be called with nc=1 thus ofdm_ncp will equal 0 so we need to correct for that where necessary.

Basically it is just a QPSK signal with BPSK pilots.

**Comment by srsampson** [comment]
```
+------------+------------ ... --------------+------------+--
| BPSK Pilot | QPSK Symbol     QPSK Symbol N | BPSK Pilot |
+------------+------------ ... --------------+------------+--
```

**Comment by drowe67** [comment]
Nice work Steve, maybe start with a low symbol rate like 100 symb/s.  Average spectrum should look like a sync function.

I guess on Rx for phase estimation we will average the single pilot of the usual 4 positions in past and future.

We will need to put some thought into UW, and also initial timing estimation - not much info to correlate on in one carrier. Might need to extend to multiple "frames".

**Comment by srsampson** [comment]
I guess in the end, we would need a symbol rate that would fit in a 300 - 3500 kHz or so bandwidth.

**Comment by srsampson** [comment]
I was using:

```
./ofdm_gen_test_bits --out test.dat --frames 100
```
and
```
./ofdm_mod --in test.dat --nc 1 --tcp 0 --ts 0.0005 --out test.raw --verbose 2 --ns 113 --tx_freq 1600 --rx_freq 1600
```

Where ts = 1/2000

Results in:
```
ofdm_bitsperframe = 224
ofdm_rowsperframe = 112
ofdm_samplesperframe = 452
```

Time-domain Spectrum seems clipped.

**Comment by drowe67** [comment]
Good point @srsampson. Unfiltered PSK at 2000 symbols/s has a main lobe 2000 Hz wide, so that should be OK.  But while developing might be nice to allow room for a few more lobes, so it's a nice scatter diagram on rx

**Comment by srsampson** [comment]
I keep rediscovering that audacity has its limitations... 

2khz-1500-center

(2 kHz 1.5 kHz center)

Looks like it's shifted left 100 Hz or so. Guess I'll check the omega function...

**Comment by srsampson** [comment]
I deleted my previous comment, as I was using the wrong signal. argh...

**Pull request closed without merging**
